/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.master.controller;




import com.maan.eway.error.Error;
import com.maan.eway.master.req.RiskMasterGetAllReq;
import com.maan.eway.master.req.RiskMasterGetReq;
import com.maan.eway.master.req.RiskMasterSaveReq;
import com.maan.eway.master.res.RiskMasterRes;
import com.maan.eway.master.service.RiskMasterService;
import com.maan.eway.req.CustomerDetailsGetAllReq;
import com.maan.eway.req.RiskDetailsGetAllReq;
import com.maan.eway.bean.RiskMaster;
import com.maan.eway.res.CommonRes;
import com.maan.eway.res.CustomerDetailsRes;
import com.maan.eway.res.DropDownRes;
import com.maan.eway.res.RiskDetailsRes;
import com.maan.eway.res.SuccessRes;
import com.maan.eway.service.CustomerDetailsService;
import com.maan.eway.service.PrintReqService;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.Collections;
import java.util.List;


/**
* <h2>RiskMasterController</h2>
*/
@RestController
@Api(tags = "MASTER : Risk Master ", description = "API's")
@RequestMapping("/master")
public class RiskMasterController {

	@Autowired
	private  RiskMasterService riskService;
	
	@Autowired
	private  PrintReqService reqPrinter;
	
	// save
		@PostMapping("/insertrisk")
		@ApiOperation(value = "This method is Insert Risk Details")
		public ResponseEntity<CommonRes> insertRisk(@RequestBody RiskMasterSaveReq req) {

			reqPrinter.reqPrint(req);
			CommonRes data = new CommonRes();

			List<Error> validation = riskService.validateRiskDetails(req);
			// validation
			if (validation != null && validation.size() != 0) {
				data.setCommonResponse(null);
				data.setIsError(true);
				data.setErrorMessage(validation);
				data.setMessage("Failed");
				return new ResponseEntity<CommonRes>(data, HttpStatus.OK);

			} else {

				// Get All
				SuccessRes res = riskService.insertRisk(req);
				data.setCommonResponse(res);
				data.setIsError(false);
				data.setErrorMessage(Collections.emptyList());
				data.setMessage("Success");

				if (res != null) {
					return new ResponseEntity<CommonRes>(data, HttpStatus.CREATED);
				} else {
					return new ResponseEntity<>(null, HttpStatus.BAD_REQUEST);
				}
			}

		}
		
		//  Get All Risk Master
		
		@PostMapping("/getallriskdetails")
		@ApiOperation("This method is getall Risk Details")
		public ResponseEntity<CommonRes> getallRiskDetails(@RequestBody RiskMasterGetAllReq req)
		{
			CommonRes data = new CommonRes();
			reqPrinter.reqPrint(req);
			
			List<RiskMasterRes> res = riskService.getallRiskDetails(req);
			data.setCommonResponse(res);
			data.setErrorMessage(Collections.emptyList());
			data.setIsError(false);
			data.setMessage("Success");
			
			if(res!= null) {
				return new ResponseEntity<CommonRes> (data, HttpStatus.CREATED);
			}
			else {
				return new ResponseEntity<> (null, HttpStatus.BAD_REQUEST);
			}
		}
		
	//  Get Active Risk Master
		
			@PostMapping("/getactiverisk")
			@ApiOperation("This method is get Active Risk Details")
			public ResponseEntity<CommonRes> getActiveRiskDetails(@RequestBody RiskMasterGetAllReq req)
			{
				CommonRes data = new CommonRes();
				reqPrinter.reqPrint(req);
				
				List<RiskMasterRes> res = riskService.getActiveRiskDetails(req);
				data.setCommonResponse(res);
				data.setErrorMessage(Collections.emptyList());
				data.setIsError(false);
				data.setMessage("Success");
				
				if(res!= null) {
					return new ResponseEntity<CommonRes> (data, HttpStatus.CREATED);
				}
				else {
					return new ResponseEntity<> (null, HttpStatus.BAD_REQUEST);
				}
			}
		
		// Get By Risk Id
		
		@PostMapping("/getbyriskid")
		@ApiOperation("This Method is to get by Risk id")
		public ResponseEntity<CommonRes> getByRiskCode(@RequestBody RiskMasterGetReq req)
		{
		CommonRes data = new CommonRes();
		RiskMasterRes res = riskService.getByRiskCode(req);
		data.setCommonResponse(res);
		data.setErrorMessage(Collections.emptyList());
		data.setIsError(false);
		data.setMessage("Success");

		if (res != null) {
			return new ResponseEntity<CommonRes>(data, HttpStatus.CREATED);

		} else {
			return new ResponseEntity<>(null, HttpStatus.BAD_REQUEST);
		}
	}

		//  Get All Customer Details With Reference Count
		
		@PostMapping("/getallriskcountetails")
		@ApiOperation("This method is getall Risk Details")
		public ResponseEntity<CommonRes> getallCustomerDetails(@RequestBody RiskDetailsGetAllReq req)
		{
			CommonRes data = new CommonRes();
			reqPrinter.reqPrint(req);
			
			List<RiskDetailsRes> res = riskService.getallRiskWithCount(req);
			data.setCommonResponse(res);
			data.setErrorMessage(Collections.emptyList());
			data.setIsError(false);
			data.setMessage("Success");
			
			if(res!= null) {
				return new ResponseEntity<CommonRes> (data, HttpStatus.CREATED);
			}
			else {
				return new ResponseEntity<> (null, HttpStatus.BAD_REQUEST);
			}
		}
		
}
