/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.admin.service;

import com.maan.eway.admin.req.BankMasterGetAllReq;
import com.maan.eway.admin.req.BankMasterGetReq;
import com.maan.eway.admin.req.BankMasterSaveReq;
import com.maan.eway.admin.req.ProductMasterGetAllReq;
import com.maan.eway.admin.req.ProductMasterGetReq;
import com.maan.eway.admin.req.ProductMasterSaveReq;
import com.maan.eway.admin.req.RegionMasterGetAllReq;
import com.maan.eway.admin.req.RegionMasterGetReq;
import com.maan.eway.admin.req.RegionMasterSaveReq;
import com.maan.eway.admin.res.BankMasterRes;
import com.maan.eway.admin.res.ProductMasterRes;
import com.maan.eway.admin.res.RegionMasterRes;
import com.maan.eway.error.Error;
import com.maan.eway.res.DropDownRes;
import com.maan.eway.res.SuccessRes;

import java.util.List;
/**
* <h2>BankMasterServiceimpl</h2>
*/
public interface ProductMasterService  {

	List<Error> validateProductDetails(ProductMasterSaveReq req);

	SuccessRes insertProduct(ProductMasterSaveReq req);

	List<ProductMasterRes> getallProductDetails(ProductMasterGetAllReq req);

	List<ProductMasterRes> getActiveProductDetails(ProductMasterGetAllReq req);

	ProductMasterRes getByProductCode(ProductMasterGetReq req);

	List<DropDownRes> getProductMasterDropdown();

	


}
