/*
 * Java domain class for entity "AcExecutiveMaster" 
 * Created on 2022-11-11 ( Date ISO 2022-11-11 - Time 13:36:48 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-11-11 ( 13:36:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;

import com.maan.eway.bean.AcExecutiveMaster;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import com.maan.eway.bean.AcExecutiveMasterId;
/**
 * <h2>AcExecutiveMasterRepository</h2>
 *
 * createdAt : 2022-11-11 - Time 13:36:48
 * <p>
 * Description: "AcExecutiveMaster" Repository
 */
 
 
 
public interface AcExecutiveMasterRepository  extends JpaRepository<AcExecutiveMaster,AcExecutiveMasterId > , JpaSpecificationExecutor<AcExecutiveMaster> {

}
