/*
 * Java domain class for entity "ClaimLoginMaster" 
 * Created on 2022-05-14 ( Date ISO 2022-05-14 - Time 15:00:24 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
* Created on 2022-05-14 ( 15:00:24 )
* Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/

package com.maan.eway.repository;

import java.math.BigDecimal;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;


import com.maan.eway.bean.CoverDocumentUploadDetails;
import com.maan.eway.bean.CoverDocumentUploadDetailsId;

/**
 * <h2>ClaimLoginMasterRepository</h2>
 *
 * createdAt : 2022-05-14 - Time 15:00:24
 * <p>
 * Description: "ClaimLoginMaster" Repository
 */

public interface CoverDocumentUploadDetailsRepository extends JpaRepository<CoverDocumentUploadDetails, CoverDocumentUploadDetailsId>,JpaSpecificationExecutor<CoverDocumentUploadDetails> {

	List<CoverDocumentUploadDetails> findByRequestRefNoAndCompanyId(String requestRefNo, String insCompanyId);
	
	List<CoverDocumentUploadDetails> findAllByOrderByDocumentRefDesc();
	
	List<CoverDocumentUploadDetails> findByRequestRefNoAndCompanyIdAndDocApplicableInAndDocApplicableIdIn(String requestRefNo, String insCompanyId,List<String> docApplicable,List<String> docApplicableId);

	List<CoverDocumentUploadDetails> findByRequestRefNoOrderByEntryDateAsc(String requestRefNo);

	CoverDocumentUploadDetails findByRequestRefNoAndDocumentRefAndDocumentId(String requestRefNo, Integer valueOf,
			Integer valueOf2);

}
