/*
 * Java domain class for entity "HomePositionMaster" 
 * Created on 2022-11-09 ( Date ISO 2022-11-09 - Time 18:32:15 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-11-09 ( 18:32:15 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;
import java.util.List;

import com.maan.eway.bean.HomePositionMaster;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import com.maan.eway.bean.HomePositionMasterId;
/**
 * <h2>HomePositionMasterRepository</h2>
 *
 * createdAt : 2022-11-09 - Time 18:32:15
 * <p>
 * Description: "HomePositionMaster" Repository
 */
 
 
 
public interface HomePositionMasterRepository  extends JpaRepository<HomePositionMaster,HomePositionMasterId > , JpaSpecificationExecutor<HomePositionMaster> {

	HomePositionMaster findByQuoteNo(String quoteNo);

//	HomePositionMaster findTop1ByCompanyIdOrderByPolicyCovertedDateDesc(String insuranceId);

	HomePositionMaster findTop1ByCompanyIdAndPolicyNoIsNotNullAndIntegrationStatusAndStatusAndEndtTypeIdIsNullOrderByPolicyCovertedDateDesc(
			String insuranceId, String string, String string2);

	HomePositionMaster findTop1ByCompanyIdAndPolicyNoIsNotNullAndIntegrationStatusAndStatusAndEndtTypeIdIsNotNullOrderByPolicyCovertedDateDesc(
			String insuranceId, String string, String string2);

	List<HomePositionMaster> findByQuoteNoIn(List<String> quoteNos);

}
