/*
 * Java domain class for entity "MailDataDetails" 
 * Created on 2023-01-07 ( Date ISO 2023-01-07 - Time 17:12:05 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-01-07 ( 17:12:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.eway.bean.MailDataDetails;


/**
 * <h2>MailDataDetailsRepository</h2>
 *
 * createdAt : 2023-01-07 - Time 17:12:05
 * <p>
 * Description: "MailDataDetails" Repository
 */
 
 
 
public interface MailDataDetailsRepository  extends JpaRepository<MailDataDetails,Long > , JpaSpecificationExecutor<MailDataDetails> {

	List<MailDataDetails> findByNotifNoOrderByPushedEntryDateDesc(Integer valueOf);

	MailDataDetails findTop1ByOrderByPushedEntryDateDesc();

}
