/*
 * Java domain class for entity "PremiaCustomerCode" 
 * Created on 2022-12-05 ( Date ISO 2022-12-05 - Time 18:53:59 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-12-05 ( 18:53:59 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;

import com.maan.eway.bean.PremiaCustomerCode;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import com.maan.eway.bean.PremiaCustomerCodeId;
/**
 * <h2>PremiaCustomerCodeRepository</h2>
 *
 * createdAt : 2022-12-05 - Time 18:53:59
 * <p>
 * Description: "PremiaCustomerCode" Repository
 */
 
 
 
public interface PremiaCustomerCodeRepository  extends JpaRepository<PremiaCustomerCode,PremiaCustomerCodeId > , JpaSpecificationExecutor<PremiaCustomerCode> {

}
