/*
 * Java domain class for entity "SessionDetails" 
 * Created on 2021-08-13 ( Date ISO 2021-08-13 - Time 15:03:28 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
* Created on 2021-08-13 ( 15:03:28 )
* Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/

package com.maan.eway.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import com.maan.eway.bean.UsertypeMaster;
import com.maan.eway.bean.UsertypeMasterId;

/**
 * <h2>SessionDetailsRepository</h2>
 *
 * createdAt : 2021-08-13 - Time 15:03:28
 * <p>
 * Description: "SessionDetails" Repository
 */

@Repository
public interface UserTypeMasterRepository extends JpaRepository<UsertypeMaster, UsertypeMasterId>, JpaSpecificationExecutor<UsertypeMaster> {

	List<UsertypeMaster> findByStatusOrderByOrderIdAsc(String string);
	
}
