/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-10-11 ( Date ISO 2022-10-11 - Time 15:28:59 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.common.service.impl;

import java.util.Collections;
import java.util.List;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.dozer.DozerBeanMapper;
import org.dozer.inject.DozerBeanContainer;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.maan.eway.bean.PersonalInfo;
import com.maan.eway.common.req.PersonalInfoSaveReq;
import com.maan.eway.common.service.PersonalInfoService;
import com.maan.eway.repository.PersonalInfoRepository;
import com.maan.eway.res.SuccessRes;
/**
* <h2>PersonalInfoServiceimpl</h2>
*/
@Service
@Transactional
public class PersonalInfoServiceImpl implements PersonalInfoService {

@Autowired
private PersonalInfoRepository repository;


private Logger log=LogManager.getLogger(PersonalInfoServiceImpl.class);
/*
public PersonalInfoServiceImpl(PersonalInfoRepository repo) {
this.repository = repo;
}

  */
 @Override
    public PersonalInfo create(PersonalInfo d) {

       PersonalInfo entity;

        try {
            entity = repository.save(d);

        } catch (Exception ex) {
			log.error(ex);
            return null;
        }
        return entity;
    }

    
    @Override
    public PersonalInfo update(PersonalInfo d) {
        PersonalInfo c;

        try {
            c = repository.saveAndFlush(d);

        } catch (Exception ex) {
			log.error(ex);
            return null;
        }
        return c;
    }

/*
    @Override
    public PersonalInfo getOne(long id) {
        PersonalInfo t;

        try {
            t = repository.findById(id).orElse(null);

        } catch (Exception ex) {
			log.error(ex);
            return null;
        }
        return t;
    }

*/
    @Override
    public List<PersonalInfo> getAll() {
        List<PersonalInfo> lst;

        try {
            lst = repository.findAll();

        } catch (Exception ex) {
			log.error(ex);
            return Collections.emptyList();
        }
        return lst;
    }


    @Override
    public long getTotal() {
        long total;

        try {
            total = repository.count();
        } catch (Exception ex) {
            log.error(ex);
			return 0;
        }
        return total;
    }


	@Override
	public SuccessRes saveCustomerDetails(PersonalInfoSaveReq req) {
		SuccessRes res = new SuccessRes();
		DozerBeanMapper dozerMapper = new DozerBeanMapper();
		try {
		//	PersonalInfo personalInfo = repository.findByReferalMaster
			
		//	PersonalInfo personalInfo = new PersonalInfo();
		//	dozerMapper.map(req, personalInfo);
			
			
			
		} catch (Exception e) {
			e.printStackTrace();
            log.info("Exception is ---> " + e.getMessage());
			return null ;
        }
        return res;
    }

/*
    @Override
    public boolean delete(long id) {
        try {
            repository.deleteById(id);
            return true;

        } catch (Exception ex) {
			log.error(ex);
            return false;
        }
    }

 */

}
