/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:27 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.admin.service.impl;

import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.modelmapper.ModelMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.google.gson.Gson;
import com.maan.eway.admin.req.BrokerCreationReq;
import com.maan.eway.admin.req.CommonLoginCreationReq;
import com.maan.eway.admin.req.CommonLoginInformationReq;
import com.maan.eway.admin.req.CommonPersonalInforReq;
import com.maan.eway.admin.service.LoginCreationService;
import com.maan.eway.bean.BranchMaster;
import com.maan.eway.bean.LoginMaster;
import com.maan.eway.bean.LoginMasterArch;
import com.maan.eway.bean.LoginUserInfo;
import com.maan.eway.bean.LoginUserInfoArch;
import com.maan.eway.error.Error;
import com.maan.eway.repository.BranchMasterRepository;
import com.maan.eway.repository.LoginMasterArchRepository;
import com.maan.eway.repository.LoginMasterRepository;
import com.maan.eway.repository.LoginUserInfoArchRepository;
import com.maan.eway.repository.LoginUserInfoRepository;
import com.maan.eway.res.LoginCreationRes;
/**
* <h2>LoginMasterServiceimpl</h2>
*/
@Service
@Transactional
public class LoginCreationServiceImpl implements LoginCreationService {

	@Autowired
	private LoginMasterRepository loginRepo;
	
	@Autowired
	private LoginMasterArchRepository loginArchRepo;
	
	@Autowired
	private LoginUserInfoRepository loginUserRepo ;
	
	@Autowired
	private LoginUserInfoArchRepository loginUserArchRepo ;
	
	@Autowired
	private BasicLoginValidationService basicValidation;
	
	@Autowired
	private BranchMasterRepository branchRepo ;

	Gson json = new Gson();


private Logger log=LogManager.getLogger(LoginCreationServiceImpl.class);
/*
public LoginMasterServiceImpl(LoginMasterRepository repo) {
this.repository = repo;
}

  */
 	@Override
    public LoginMaster create(LoginMaster d) {

       LoginMaster entity;

        try {
            entity = loginRepo.save(d);

        } catch (Exception ex) {
			log.error(ex);
            return null;
        }
        return entity;
    }

    
    @Override
    public LoginMaster update(LoginMaster d) {
        LoginMaster c;

        try {
            c = loginRepo.saveAndFlush(d);

        } catch (Exception ex) {
			log.error(ex);
            return null;
        }
        return c;
    }

/*
    @Override
    public LoginMaster getOne(long id) {
        LoginMaster t;

        try {
            t = repository.findById(id).orElse(null);

        } catch (Exception ex) {
			log.error(ex);
            return null;
        }
        return t;
    }

*/
    @Override
    public List<LoginMaster> getAll() {
        List<LoginMaster> lst;

        try {
            lst = loginRepo.findAll();

        } catch (Exception ex) {
			log.error(ex);
            return Collections.emptyList();
        }
        return lst;
    }


    @Override
    public long getTotal() {
        long total;

        try {
            total = loginRepo.count();
        } catch (Exception ex) {
            log.error(ex);
			return 0;
        }
        return total;
    }


	@Override
	public List<Error> validateBrokerCreation(BrokerCreationReq req) {
		List<Error> errors = new ArrayList<Error>();
		ModelMapper mapper = new ModelMapper();
		mapper.getConfiguration().setAmbiguityIgnored(true);	
		try {
			
			// Common Errors
			CommonLoginCreationReq commonReq = new CommonLoginCreationReq();
			mapper.map(req, commonReq);
			List<Error>  commonErrors = basicValidation.commonLoginCreationValidation(commonReq) ;
			if(commonErrors.size()>0  ) {
				errors.addAll(commonErrors);
			}
			
			// Additional Errors
			
		} catch (Exception e) {
			e.printStackTrace();
			log.info("Exception is --->" + e.getMessage());
			errors.add(new Error("07", "Common Error", e.getMessage() ));
			return errors;
		}
		return errors;
	}

	
	
	

	@Transactional
	@Override
	public LoginCreationRes createBroker(BrokerCreationReq req) {
		LoginCreationRes res = new LoginCreationRes();
		ModelMapper mapper = new ModelMapper();
		mapper.getConfiguration().setAmbiguityIgnored(true);	
		try {	
			List<String> branchList = req.getLoginInformation().getAttachedBranches();	
			List<BranchMaster> findBranches = branchRepo.findByBranchCodeIn(branchList);
			List<String> regionList =  findBranches.stream().map(o ->  o.getRegionCode() ).collect(Collectors.toList());
			List<String> companyList = findBranches.stream().map(o ->  o.getCompanyId() ).collect(Collectors.toList());
			
			// Remove Duplicates
			regionList = regionList.stream().distinct().collect(Collectors.toList()); 
			companyList = companyList.stream().distinct().collect(Collectors.toList());
			
			CommonLoginCreationReq commonReq = mapper.map(req, CommonLoginCreationReq.class );
			commonReq.getLoginInformation().setAttachedRegions(regionList);
			commonReq.getLoginInformation().setAttachedCompanies(companyList);
			
			LoginMaster loginData  = loginRepo.findByLoginId(req.getLoginInformation().getLoginId()  );
			
			String saveRes = "";
			if (loginData ==null) {
				// Save
				saveRes =   newLoginInsert(commonReq) ;
				res.setResponse("Saved Successfully");
				
			} else {
				// Update
				saveRes = updateLoginDetails(commonReq);
				res.setResponse("Updated Successfully");
			}
			
			if(! saveRes.equalsIgnoreCase("Success")  ) {
				return null; 
			}
			
		} catch (Exception e) {
			e.printStackTrace();
			log.info("Exception is --->" + e.getMessage());
			return null; 
		}
		return res ;
	}

	
	
	
	
	// Login Save Method
	
	public String newLoginInsert(CommonLoginCreationReq req ) {
		String res = "" ;  
		ModelMapper mapper = new ModelMapper();
		mapper.getConfiguration().setAmbiguityIgnored(true);	
		try {
			CommonLoginInformationReq loginReq = req.getLoginInformation() ;
			
		//	passwordEnc passEnc = new passwordEnc();
			String newpass = "BgBn8jBhAYu3paFVGk54PlgnOGo=";// passEnc.crypt(loginReq.getPassword().trim());
			Instant now = Instant.now();
			Instant after = now.plus(Duration.ofDays(45));
			Date dateAfter = Date.from(after);
			Long count = loginRepo.count();
			Long countId = 10001 + count ; 
			
			String branches  =  String.join(",", loginReq.getAttachedBranches());
			String regions   =  String.join(",", loginReq.getAttachedRegions());
			String companies =  String.join(",", loginReq.getAttachedCompanies());
			
			// Login Master Insert
			LoginMaster saveLogin = new LoginMaster();
			mapper.map(loginReq, saveLogin);
			saveLogin.setLoginId(loginReq.getLoginId());
			saveLogin.setAttachedBranches(branches);
			saveLogin.setAttachedRegions(regions);
			saveLogin.setAttachedCompanies(companies);
			saveLogin.setOaCode(countId.toString());
			saveLogin.setAgencyCode(countId.toString());
			saveLogin.setEntryDate(new Date());
			saveLogin.setUpdatedDate(new Date());
			saveLogin.setUpdatedBy(loginReq.getCreatedBy());
			saveLogin.setPassword(newpass);
			saveLogin.setPwdCount("0");				
			saveLogin.setLpassDate(dateAfter);
			loginRepo.saveAndFlush(saveLogin);
				
			// Login User Details Insert
			CommonPersonalInforReq personalReq = req.getPersonalInformation() ;
			LoginUserInfo userInfo = new LoginUserInfo(); 
			mapper.map(personalReq, userInfo);
			userInfo.setEntryDate(new Date());
			userInfo.setUpdatedDate(new Date());
			userInfo.setUpdatedBy(loginReq.getCreatedBy());
			loginUserRepo.saveAndFlush(userInfo);
			
			res = "Success" ; 
		} catch (Exception e) {
			e.printStackTrace();
			log.info("Exception is --->" + e.getMessage());
			return null;
		}
		return res;
	}
	
	
	// Login Save Method
	
	public String updateLoginDetails(CommonLoginCreationReq req ) {
		String res = "";
		ModelMapper mapper = new ModelMapper();
		mapper.getConfiguration().setAmbiguityIgnored(true);
		SimpleDateFormat idf = new SimpleDateFormat("yyMMddhhssmmss"); 
		try {
			// Find Data 
			String loginId = req.getLoginInformation().getLoginId() ;
			LoginMaster findLogin = loginRepo.findByLoginId(loginId);
			LoginUserInfo findUserInfo = loginUserRepo.findByLoginId(loginId);
			
			// Save in Arch tables
			String archId = "AI-" + idf.format(new Date());
			LoginMasterArch  loginArch = mapper.map(findLogin, LoginMasterArch.class )  ;
			loginArch.setArchId(archId);
			loginArchRepo.saveAndFlush(loginArch);
			LoginUserInfoArch userArch = mapper.map(findUserInfo, LoginUserInfoArch.class )  ;  
			userArch.setArchId(archId);
			loginUserArchRepo.saveAndFlush(userArch);
			
			// Delete Old Records
			LoginMaster  updateLogin = findLogin;
			loginRepo.delete(findLogin);
			LoginUserInfo updateUser = findUserInfo;
			loginUserRepo.delete(findUserInfo);
			
			// Update Login Master
			CommonLoginInformationReq loginReq = req.getLoginInformation() ;
			String branches  =  String.join(",", loginReq.getAttachedBranches());
			String regions   =  String.join(",", loginReq.getAttachedRegions());
			String companies =  String.join(",", loginReq.getAttachedCompanies());
			
			mapper.map(loginReq, updateLogin);
			updateLogin.setUpdatedDate(new Date());
			updateLogin.setUpdatedBy(loginReq.getCreatedBy());
			updateLogin.setLoginId(loginReq.getLoginId());
			updateLogin.setAttachedBranches(branches);
			updateLogin.setAttachedRegions(regions);
			updateLogin.setAttachedCompanies(companies);
			loginRepo.saveAndFlush(updateLogin);
			
			log.info( "Login Master Updated Details ---> " + json.toJson(updateLogin) );
			
			// Update User Info 
			CommonPersonalInforReq personalReq = req.getPersonalInformation() ;
			mapper.map(personalReq , updateUser);
			updateUser.setUpdatedDate(new Date());
			updateUser.setUpdatedBy(loginReq.getCreatedBy());
			loginUserRepo.saveAndFlush(updateUser);
			log.info( "Login User Info Updated Details ---> " + json.toJson(updateUser) );
			
			res = "Success" ;
		} catch (Exception e) {
			e.printStackTrace();
			log.info("Exception is --->" + e.getMessage());
			return null;
		}
		return res;
	}
	
/*
    @Override
    public boolean delete(long id) {
        try {
            repository.deleteById(id);
            return true;

        } catch (Exception ex) {
			log.error(ex);
            return false;
        }
    }

 */

}
