/*
 * Java domain class for entity "EserviceCustomerDetails" 
 * Created on 2022-09-23 ( Date ISO 2022-09-23 - Time 15:08:00 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.eway.domain;

import java.io.Serializable;

import lombok.*;
import java.util.Date;


import java.util.Date;
import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonProperty;



/**
 * Domain class for entity "EserviceCustomerDetails"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class EserviceCustomerDetailsDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Customerid")
    private String     customerId   ;
	@JsonProperty("Gstno")
    private String     gstNo        ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Companyid")
    private String     companyId    ;
	@JsonProperty("Countrycode")
    private String     countryCode  ;
	@JsonProperty("Regioncode")
    private String     regionCode   ;
	@JsonProperty("Branchcode")
    private String     branchCode   ;
	@JsonProperty("Statecode")
    private Integer    stateCode    ;
	@JsonProperty("Statename")
    private String     stateName    ;
	@JsonProperty("Citycode")
    private Integer    cityCode     ;
	@JsonProperty("Cityname")
    private String     cityName     ;
	@JsonProperty("Requestid")
    private String     requestId    ;
	@JsonProperty("Companycode")
    private String     companyCode  ;
	@JsonProperty("Systemcode")
    private String     systemCode   ;
	@JsonProperty("Callbackurl")
    private String     callBackUrl  ;
	@JsonProperty("Insurancecompanycode")
    private String     insuranceCompanyCode ;
	@JsonProperty("Trancompanycode")
    private String     tranCompanyCode ;
	@JsonProperty("Covernotetypeid")
    private Integer    coverNoteTypeId ;
	@JsonProperty("Covernotetypedesc")
    private String     coverNoteTypeDesc ;
	@JsonProperty("Covernotenumber")
    private String     coverNoteNumber ;
	@JsonProperty("Prevconvernotereferencenumber")
    private String     prevConverNoteReferenceNumber ;
	@JsonProperty("Salepointcode")
    private String     salePointCode ;
	@JsonProperty("Covernotestartdate")
    private Date       coverNoteStartDate ;
	@JsonProperty("Covernoteenddate")
    private Date       coverNoteEndDate ;
	@JsonProperty("Covernotedesc")
    private String     coverNoteDesc ;
	@JsonProperty("Operativeclause")
    private String     operativeClause ;
	@JsonProperty("Paymentmode")
    private Integer    paymentMode  ;
	@JsonProperty("Paymentmodedesc")
    private String     paymentModeDesc ;
	@JsonProperty("Currenycode")
    private String     currenyCode  ;
	@JsonProperty("Exchangerate")
    private Double     exchangeRate ;
	@JsonProperty("Totalpremiumexcludingtax")
    private Double     totalPremiumExcludingTax ;
	@JsonProperty("Totalpremiumincludingtax")
    private Double     totalPremiumIncludingTax ;
	@JsonProperty("Commissionpaid")
    private Double     commissionPaid ;
	@JsonProperty("Commissionrate")
    private Double     commissionRate ;
	@JsonProperty("Officername")
    private String     officerName  ;
	@JsonProperty("Officertitle")
    private String     officerTitle ;
	@JsonProperty("Productcode")
    private String     productCode  ;
	@JsonProperty("Endorsementtype")
    private Integer    endorsementType ;
	@JsonProperty("Endorsementtypedesc")
    private String     endorsementTypeDesc ;
	@JsonProperty("Endorsementreason")
    private String     endorsementReason ;
	@JsonProperty("Endoresementpremiumearned")
    private Double     endoresementPremiumEarned ;
	@JsonProperty("Riskcode")
    private String     riskCode     ;
	@JsonProperty("Suminsured")
    private Double     sumInsured   ;
	@JsonProperty("Suminsuresequivalent")
    private Double     sumInsuresEquivalent ;
	@JsonProperty("Premiumrate")
    private Double     premiumRate  ;
	@JsonProperty("Premiumbeforediscount")
    private Double     premiumBeforeDiscount ;
	@JsonProperty("Premiumafterdiscount")
    private Double     premiumAfterDiscount ;
	@JsonProperty("Premiumexcludingtaxequivalent")
    private Double     premiumExcludingTaxEquivalent ;
	@JsonProperty("Premiumexcludingtax")
    private Double     premiumExcludingTax ;
	@JsonProperty("Premiumincludingtax")
    private Double     premiumIncludingTax ;
	@JsonProperty("Discounttype")
    private Integer    discountType ;
	@JsonProperty("Discounttypedesc")
    private String     discountTypeDesc ;
	@JsonProperty("Discountrate")
    private Double     discountRate ;
	@JsonProperty("Discountamount")
    private Double     discountAmount ;
	@JsonProperty("Taxcode")
    private String     taxCode      ;
	@JsonProperty("Istaxexemptedid")
    private String     isTaxExemptedId ;
	@JsonProperty("Istaxexemptedtypedesc")
    private String     isTaxExemptedTypeDesc ;
	@JsonProperty("Taxexcemptiontypeid")
    private String     taxExcemptionTypeId ;
	@JsonProperty("Taxexcemptiontypedesc")
    private String     taxExcemptionTypeDesc ;
	@JsonProperty("Taxexemptionreference")
    private String     taxExemptionReference ;
	@JsonProperty("Taxrate")
    private Double     taxRate      ;
	@JsonProperty("Taxamount")
    private Double     taxAmount    ;
	@JsonProperty("Subjectmatterreference")
    private String     subjectMatterReference ;
	@JsonProperty("Subjectmatterdesc")
    private String     subjectMatterDesc ;
	@JsonProperty("Addonreference")
    private String     addonReference ;
	@JsonProperty("Addondesc")
    private String     addonDesc    ;
	@JsonProperty("Addonamount")
    private Double     addonAmount  ;
	@JsonProperty("Addonpremiumrate")
    private Double     addonPremiumRate ;
	@JsonProperty("Policyholdername")
    private String     policyHolderName ;
	@JsonProperty("Policyholderbirthdate")
    private Date       policyHolderBirthDate ;
	@JsonProperty("Policyholdertypeid")
    private Integer    policyHolderTypeId ;
	@JsonProperty("Policyholdertypedesc")
    private String     policyHolderTypeDesc ;
	@JsonProperty("Policyholderidnumber")
    private String     policyHolderIdNumber ;
	@JsonProperty("Policyholderidtypeid")
    private Integer    policyHolderIdTypeId ;
	@JsonProperty("Policyholderidtypedesc")
    private String     policyHolderIdTypeDesc ;
	@JsonProperty("Genderid")
    private String     genderId     ;
	@JsonProperty("Gendedesc")
    private String     gendeDesc    ;
	@JsonProperty("Street")
    private String     street       ;
	@JsonProperty("Policyholdermobilenumber")
    private String     policyHolderMobileNumber ;
	@JsonProperty("Policyholderfax")
    private String     policyHolderFax ;
	@JsonProperty("Postaladdress")
    private String     postalAddress ;
	@JsonProperty("Emailaddress")
    private String     emailAddress ;
	@JsonProperty("Mobileno1")
    private String     mobileNo1    ;
	@JsonProperty("Mobileno2")
    private String     mobileNo2    ;
	@JsonProperty("Mobileno3")
    private String     mobileNo3    ;
	@JsonProperty("Email1")
    private String     email1       ;
	@JsonProperty("Email2")
    private String     email2       ;
	@JsonProperty("Email3")
    private String     email3       ;
	@JsonProperty("Preferredsystemnotificationid")
    private Integer    preferredSystemNotificationId ;
	@JsonProperty("Preferredsystemnotification")
    private String     preferredSystemNotification ;
	@JsonProperty("Selectlanguageid")
    private Integer    selectLanguageId ;
	@JsonProperty("Selectlanguagedesc")
    private String     selectLanguageDesc ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

      
	  
	  
}
