/*
 * Java domain class for entity "CoverMaster" 
 * Created on 2022-09-02 ( Date ISO 2022-09-02 - Time 18:14:51 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.eway.master.req;



import lombok.*;

import java.io.Serializable;
import java.util.Date;


import java.util.Date;
import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;



/**
 * Domain class for entity "CoverMaster"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class CoverMasterSaveReq implements Serializable {

    private static final long serialVersionUID = 1L;

	@JsonProperty("CoverId")
	private Integer coverId;
	
	@JsonProperty("SectionId")
	private Integer sectionId;
	
	@JsonProperty("ProductId")
	private Integer productId;
	
	@JsonProperty("CompanyId")
	private String companyId;
	
	@JsonFormat(pattern="dd/MM/yyyy")
	@JsonProperty("EffectiveDate")
	private Date effectiveDate;

	@JsonProperty("CoverName")
	private String coverName;
	
	@JsonProperty("CoverDesc")
	private String coverDesc;
	
	@JsonProperty("Status")
	private String status;

	@JsonProperty("CoreAppCode")
	private String coreAppCode;

	@JsonProperty("AmendId")
	private Integer amendId;

	@JsonProperty("Remarks")
	private String remarks;  
}
