/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-09-02 ( Date ISO 2022-09-02 - Time 18:14:52 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.service.impl;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Optional;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Expression;
import javax.persistence.criteria.Order;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import javax.persistence.criteria.Subquery;

import org.apache.commons.lang3.StringUtils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.dozer.DozerBeanMapper;
import org.hibernate.Session;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.jpa.provider.HibernateUtils;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.google.gson.Gson;
import com.maan.eway.bean.CustomerDetails;
import com.maan.eway.bean.CustomerDetailsId;
import com.maan.eway.bean.CustomerRelationship;
import com.maan.eway.bean.HomePositionMaster;
import com.maan.eway.bean.LoginMaster;
import com.maan.eway.master.req.CustomerDetailsGetAllReq;
import com.maan.eway.master.req.CustomerGetReq;
import com.maan.eway.master.req.CustomerSaveReq;
import com.maan.eway.master.res.CustomerGetRes;
import com.maan.eway.master.res.CustomerGetallCriteriaRes;
import com.maan.eway.master.res.CustomerGetallRes;
import com.maan.eway.master.service.CustomerDetailsService;
import com.maan.eway.repository.CustomerDetailsRepository;
import com.maan.eway.repository.CustomerRelationshipRepository;
import com.maan.eway.repository.LoginMasterRepository;
import com.maan.eway.res.SuccessRes;
import com.maan.eway.error.Error;
/**
* <h2>CustomerDetailsServiceimpl</h2>
*/
@Service
@Transactional
public class CustomerDetailsServiceImpl implements CustomerDetailsService {

@PersistenceContext
private EntityManager em;

@Autowired
private CustomerDetailsRepository repository;

@Autowired
private CustomerRelationshipRepository relationrepo;

@Autowired
private LoginMasterRepository loginrepo;

Gson json = new Gson();

private Logger log=LogManager.getLogger(CustomerDetailsServiceImpl.class);


	@Override
	public SuccessRes savecustomer(CustomerSaveReq req) {
		SuccessRes res = new SuccessRes();
		DozerBeanMapper mapper = new DozerBeanMapper();
		try {
			Long newId =0L;
			CustomerDetails ent = new CustomerDetails();
	
			ent = mapper.map(req, CustomerDetails.class);
			newId = repository.count()+10001;
			ent.setGstNo(req.getGstNo());
			ent.setEntryDate(new Date());
			ent.setCustomerId(Integer.valueOf(newId.toString()));
			ent.setStatus("Y");
			ent.setUpdatedBy(req.getCreatedBy());
			ent.setUpdatedDate(new Date());
			ent.setVrngst(req.getGstNo());
			res.setSuccessId(newId.toString());
			res.setResponse("Inserted Successfully");
	
			repository.save(ent);
			
			LoginMaster login = loginrepo.findByLoginId(req.getCreatedBy());
			CustomerRelationship cus = new CustomerRelationship();
			cus.setBranchCode(req.getBranchCode());
			cus.setBrokerId(Integer.valueOf(login.getOaCode()));
			cus.setCompanyId(req.getCompanyId());
			cus.setCreatedBy(req.getCreatedBy());
			cus.setCustomerId(Integer.valueOf(ent.getCustomerId()));
			cus.setEntryDate(new Date());
			cus.setGstNo(req.getGstNo());
			cus.setStatus("Y");
			relationrepo.save(cus);		
		}
		catch(Exception e) {
			e.printStackTrace();
			log.info("Log Details"+e.getMessage());
			return null;
		}
		return res;
	}
	
	
	@Override
	public CustomerGetRes getcustomer(CustomerGetReq req) {
		CustomerGetRes res = new CustomerGetRes();
		DozerBeanMapper mapper = new DozerBeanMapper();
		try {
			CustomerDetails data = repository.findByCustomerId(Integer.valueOf(req.getCustomerId()));
			res =mapper.map(data,CustomerGetRes.class);
			}
		catch(Exception e) {
			e.printStackTrace();
			log.info("Log Details"+e.getMessage());
			return null;
		}
		return res;
	}
	
	
	@Override
	public List<CustomerGetallRes> getallcustomer(CustomerDetailsGetAllReq req) {
		List<CustomerGetallRes> resList  = new ArrayList<CustomerGetallRes>();
		DozerBeanMapper mapper = new DozerBeanMapper();
		try {
			
			CriteriaBuilder cb = em.getCriteriaBuilder();
			CriteriaQuery<CustomerGetallCriteriaRes> query = cb.createQuery(CustomerGetallCriteriaRes.class);
			List<CustomerGetallCriteriaRes> list = new ArrayList<CustomerGetallCriteriaRes>();
			Root<CustomerDetails> c =query.from(CustomerDetails.class);
		
			// Customer Id Filter
			Subquery<Long> customerIds = query.subquery(Long.class);
			Root<CustomerRelationship> cr = customerIds.from(CustomerRelationship.class);
			
			customerIds.select(cr.get("customerId"));
			Predicate cr1 = cb.equal(cr.get("createdBy"), req.getCreatedBy() );
			Predicate cr2 = cb.equal(cr.get("companyId"), req.getInsuranceId());
			customerIds.where(cr1,cr2);
			
			// Product Count
			// Product Count
			Subquery<Long> productCount = query.subquery(Long.class);
			Root<HomePositionMaster> hm= productCount.from(HomePositionMaster.class);
			
			productCount.select( cb.countDistinct(hm.get("productId")) );
			Predicate hm1 = cb.equal(hm.get("loginId"), c.get("createdBy"));
			Predicate hm2 = cb.equal(hm.get("customerId"), c.get("customerId"));
			productCount.where(hm1,hm2); 
			
				
			query.multiselect(c.get("customerId").alias("customerId"),c.get("gstNo").alias("gstNo"),
					c.get("companyId").alias("companyId"),c.get("branchCode").alias("branchCode"),
					c.get("clientName").alias("clientName"),c.get("dateOfBirth").alias("dateOfBirth"),
					c.get("createdBy").alias("createdBy"),c.get("mobileNo1").alias("mobileNo1")		,
					c.get("email1").alias("email1") , productCount.alias("productCount") ,
					c.get("updatedDate").alias("updatedDate") , c.get("updatedBy").alias("updatedBy") ,
					c.get("entryDate").alias("entryDate"));
			
			// Order By
			List<Order> orderList = new ArrayList<Order>();
			orderList.add(cb.desc(c.get("updatedDate")));
			Expression<String>e0= c.get("customerId");
			Predicate n1 = e0.in(customerIds);	
			query.where(n1).orderBy(orderList);
			TypedQuery<CustomerGetallCriteriaRes> result = em.createQuery(query);
			// Limit Offset
			int limit = StringUtils.isBlank(req.getLimit()) ? 0 : Integer.valueOf(req.getLimit());
			int offset = StringUtils.isBlank(req.getOffset()) ? 100 : Integer.valueOf(req.getOffset());
			result.setFirstResult(limit * offset);
			result.setMaxResults(offset);
			list= result.getResultList();
			
			for(CustomerGetallCriteriaRes data : list) {
				CustomerGetallRes res = new CustomerGetallRes();
				res = mapper.map(data, CustomerGetallRes.class);
				resList.add(res);
			}
			}
		catch(Exception e) {
			e.printStackTrace();
			log.info("Log Details"+e.getMessage());
			return null;
		}
		return resList;
	}


	@Override
	public SuccessRes updateCustomer(CustomerSaveReq req) {
		SuccessRes res = new SuccessRes();
		//DozerBeanMapper mapper = new DozerBeanMapper();
		try {
			Long newId =0L;
			CustomerDetails ent = repository.findByCustomerId(Integer.valueOf(req.getCustomerId()))  ;
	
		//	ent = mapper.map(req, CustomerDetails.class);
			ent.setUpdatedBy(req.getCreatedBy());
			ent.setUpdatedDate(new Date());
			res.setSuccessId(req.getCustomerId());
			res.setResponse("Updated Successfully");
	
			repository.save(ent);
			
			LoginMaster login = loginrepo.findByLoginId(req.getCreatedBy());
			CustomerRelationship cus = new CustomerRelationship();
			CustomerRelationship  findRelation = relationrepo.findByCustomerIdAndCreatedBy(Integer.valueOf(req.getCustomerId()) , req.getCreatedBy());
			
			if(findRelation != null ) {
				cus = findRelation ;
			} else {
				cus.setCustomerId(Integer.valueOf(ent.getCustomerId()));
				cus.setEntryDate(new Date());
				cus.setCreatedBy(req.getCreatedBy());
				cus.setBranchCode(req.getBranchCode());
				cus.setBrokerId(Integer.valueOf(login.getOaCode()));
				cus.setCompanyId(req.getCompanyId());
				cus.setStatus("Y");
				cus.setGstNo(req.getGstNo());
			}
			cus.setUpdatedBy(req.getCreatedBy());
			cus.setUpdatedDate(new Date());
			relationrepo.save(cus);		
		}
		catch(Exception e) {
			e.printStackTrace();
			log.info("Log Details"+e.getMessage());
			return null;
		}
		return res;
	}




}
