/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-09-06 ( Date ISO 2022-09-06 - Time 11:31:31 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.service.impl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.maan.eway.repository.SectionDetailsRepository;
import com.maan.eway.bean.SectionDetails;
import com.maan.eway.service.SectionDetailsService;

import java.util.Collections;
import java.util.List;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
/**
* <h2>SectionDetailsServiceimpl</h2>
*/
@Service
@Transactional
public class SectionDetailsServiceImpl implements SectionDetailsService {

@Autowired
private SectionDetailsRepository repository;


private Logger log=LogManager.getLogger(SectionDetailsServiceImpl.class);
/*
public SectionDetailsServiceImpl(SectionDetailsRepository repo) {
this.repository = repo;
}

  */
 @Override
    public SectionDetails create(SectionDetails d) {

       SectionDetails entity;

        try {
            entity = repository.save(d);

        } catch (Exception ex) {
			log.error(ex);
            return null;
        }
        return entity;
    }

    
    @Override
    public SectionDetails update(SectionDetails d) {
        SectionDetails c;

        try {
            c = repository.saveAndFlush(d);

        } catch (Exception ex) {
			log.error(ex);
            return null;
        }
        return c;
    }

/*
    @Override
    public SectionDetails getOne(long id) {
        SectionDetails t;

        try {
            t = repository.findById(id).orElse(null);

        } catch (Exception ex) {
			log.error(ex);
            return null;
        }
        return t;
    }

*/
    @Override
    public List<SectionDetails> getAll() {
        List<SectionDetails> lst;

        try {
            lst = repository.findAll();

        } catch (Exception ex) {
			log.error(ex);
            return Collections.emptyList();
        }
        return lst;
    }


    @Override
    public long getTotal() {
        long total;

        try {
            total = repository.count();
        } catch (Exception ex) {
            log.error(ex);
			return 0;
        }
        return total;
    }

/*
    @Override
    public boolean delete(long id) {
        try {
            repository.deleteById(id);
            return true;

        } catch (Exception ex) {
			log.error(ex);
            return false;
        }
    }

 */

}
