#65 server


spring.datasource.url = jdbc:mysql://3.6.61.228:3306/ewayglobal?useSSL=false
spring.datasource.username=root
spring.datasource.password=P@Nn!Y!NS3LV@n@1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


jasper.datasourceby.jndi=N
#spring.datasource.jndi-name=java:comp/env/claimApi

# Swaggger
spring.mvc.pathmatch.matching-strategy=ant-path-matcher

#Common Path Details
file.directoryPath=\\home\\ubuntuCommonPath\\EwayPortal\\OrginalPath\\
file.compressedImg=\\home\\ubuntuCommonPath\\EwayPortal\\CompressedImg\\

rating.upload.path=\\home\\ubuntuCommonPath\\EwayPortal\\RatingFilePath\\


# excel upload properties
tira.api=http://192.168.1.42:8085/regulatory/showvehicleinfo
save.vehicle.api=http://192.168.1.42:8085/api/savemotordetails
premium.calc.api=http://192.168.1.42:8086/calculator/calc
employee.save.api=http://192.168.1.42:8085/api/saveproductemployees
employee.add.api=http://192.168.1.42:8085/api/proceedemployees
employee.merge.api=http://192.168.1.42:8085/api/saveemployees
employee.validation.api=http://192.168.1.42:8085/api/validateproductemployeesdetailsexcel
employee.delete.api=http://192.168.1.42:8085/api/deleteallproductemployees
employee.count.api=http://192.168.1.42:8086/quote/productemployeecount
passenger.save.api=http://192.168.1.42:8085/api/savepassengers
#premia.customer.api= http://localhost:5051/api/getpremiacustomerdetails
save.vehicleInfo.api=http://192.168.1.42:8085/regulatory/savevehicleinfo
premia.customer.api= http://192.168.1.42:5051/api/getpremiacustomerdetails
#save.vehicleInfo.api=http://192.168.1.19:8085/regulatory/savevehicleinfo

#kenyaReport
generateToken=http://192.168.0.76:8086/auth/generateToken
generateReport=http://192.168.0.76:8086/common/generateReport
generatecustomerdetails=http://192.168.0.76:8086/common/generateReport

ClaimBasicAuthPass=claim123#
ClaimBasicAuthName=claim


datamanipulation.password=Admin@01


#Eway BasicAUth
EwayBasicAuthName=ewayapi
EwayBasicAuthPass=ewayapi123#
SequenceGenerateUrl=http://65.0.113.151:8085/EwayCommonApi/api/generatesequence

# Excel configuration commands
spring.batch.job.enabled=true
spring.batch.jdbc.initialize-schema=always
excel.upload.path=\\home\\ubuntuCommonPath\\EwayPortal\\ExcelUpload\\Excel\\
csv.upload.path=\\home\\ubuntuCommonPath\\EwayPortal\\ExcelUpload\\Csv\\
#Multi Part File Size
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


