/*
 * Created on 2022-11-21 ( 15:19:53 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import lombok.*;
import jakarta.persistence.*;
import java.io.Serializable;
import java.util.List;


import java.util.Date;

/**
 * Composite primary key for entity "CompanyProductMaster" ( stored in table "company_product_master" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class CompanyProductMasterId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private String     companyId ;
    
    private Integer    productId ;
    
 //   private Date       effectiveDateStart ;
    
 //   private Date       effectiveDateEnd ;
    private Integer    amendId ;

     
}
