/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-09-30 ( Date ISO 2022-09-30 - Time 18:45:30 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-09-30 ( 18:45:30 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "CoverMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(CoverMasterId.class)
@Table(name="cover_master")


public class CoverMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="COVER_ID", nullable=false)
    private Integer    coverId ;

    @Id
    @Column(name="SUB_COVER_ID", nullable=false)
    private Integer    subCoverId ;

    @Id
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_START", nullable=false)
    private Date       effectiveDateStart ;

    @Id
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_END", nullable=false)
    private Date       effectiveDateEnd ;

    //--- ENTITY DATA FIELDS 
    @Column(name="SUB_COVER_YN", length=1)
    private String     subCoverYn ;

    @Column(name="SUB_COVER_NAME", length=300)
    private String     subCoverName ;

    @Column(name="COVER_NAME", length=100)
    private String     coverName ;

    @Column(name="SUB_COVER_DESC", length=300)
    private String     subCoverDesc ;

    @Column(name="COVER_DESC", length=300)
    private String     coverDesc ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="RATING_ID")
    private Integer    ratingId ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="COVERAGE_TYPE", length=1)
    private String     coverageType ;

    @Column(name="COVERAGE_TYPE_DESC", length=100)
    private String     coverageTypeDesc ;

    @Column(name="COVERAGE_LIMIT")
    private Double     coverageLimit ;

    @Column(name="REGULATORY_CODE", length=20,nullable=false)
    private String    regulatoryCode ;

    @Column(name="CALC_TYPE", length=1)
    private String     calcType ;

    @Column(name="AMEND_ID")
    private Integer    amendId ;

    @Column(name="CALC_TYPE_DESC", length=100)
    private String     calcTypeDesc ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="BASE_RATE")
    private Double     baseRate ;

    @Column(name="EXCESS")
    private Double     excess ;

    @Column(name="MIN_PREMIUM")
    private Double     minPremium ;

    @Column(name="MIN_SUMINSURED")
    private Double     minSuminsured ;

    @Column(name="TIRA_CODE", length=20)
    private String     tiraCode ;

    @Column(name="CREATED_BY", length=100)
    private String     createdBy ;

    @Column(name="MAX_SUMINSURED")
    private Double     maxSuminsured ;

    @Column(name="FACTOR_TYPE_ID")
    private Integer    factorTypeId ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



