/*
 * Created on 2022-11-21 ( 15:20:04 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;



/**
 * Composite primary key for entity "EservicePersonalAccident" ( stored in table "eservice_personal_accident" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class EservicePersonalAccidentId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private String     requestReferenceNo ;
    
    private Integer    sectionId ;
    
    private Integer    locationId ;
    
    private Integer    customerId ;
    
    private String     companyId ;
    
    private String     branchCode ;
    
    private Integer    personId ;
    
     
}
