/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2024-09-19 ( Date ISO 2024-09-19 - Time 13:48:01 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2024-09-19 ( 13:48:01 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import java.io.Serializable;
import java.math.BigDecimal;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
 




/**
* Domain class for entity "FieldQueryTablequery"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(FieldQueryTablequeryId.class)
@Table(name="field_query_tablequery")


public class FieldQueryTablequery implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="Query_id", nullable=false)
    private BigDecimal queryId ;

 
    //--- ENTITY DATA FIELDS 
    @Column(name="Query_name")
    private String     queryName ;

    @Column(name="SQL_QUERY")
    private String   sqlQuery  ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



