/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2024-08-27 ( Date ISO 2024-08-27 - Time 16:00:13 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2024-08-27 ( 16:00:13 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import java.io.Serializable;
import java.math.BigDecimal;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "FlowFieldDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(FlowFieldDetailsId.class)
@Table(name="flow_field_details")


public class FlowFieldDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="COMPANY_ID", nullable=false)
    private BigDecimal companyId ;

    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private BigDecimal productId ;

    @Id
    @Column(name="INTEG_TYPE")
    private String integType;    
    
    @Id
    @Column(name="KEY_ID", nullable=false)
    private BigDecimal keyId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="JSON_KEY", length=50)
    private String     jsonKey ;

    @Column(name="IS_HEADER", length=5)
    private String     isHeader ;

    @Column(name="HEADER_KEYID", length=50)
    private String     headerKeyid ;

    @Column(name="ISARRAY", length=5)
    private String     isarray ;

    @Column(name="DATATYPE", length=15)
    private String     datatype ;

    @Column(name="PATTERN", length=30)
    private String     pattern ;

    @Column(name="DEFAULT_YN", length=5)
    private String     defaultYn ;

    @Column(name="DEFAULT_VALUE", length=50)
    private String     defaultValue ;

    @Column(name="STATUS", length=5)
    private String     status ;

    @Column(name="QUERY_ID")
    private BigDecimal queryId ;
    
    @Column(name="QUERY_COL")
    private String queryCol ;
    
    @Column(name="QUERY_ALIAS")
    private String queryAlias;
    
    
    //--- ENTITY LINKS ( RELATIONSHIP )


}



