/*
 * Created on 2022-01-05 ( 16:11:06 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import java.io.Serializable;
import java.util.Date;

import lombok.Getter;
import lombok.Setter;


@Getter
@Setter
public class NotifTemplateMasterId implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY KEY ATTRIBUTES
	private Integer sno;

	private String insId;

	private String queryKey;

	private Date effectiveDate;

	private Integer amendid;
}
