/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-11-21 ( Date ISO 2022-11-21 - Time 15:20:23 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-11-21 ( 15:20:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "OneTimeTableDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="one_time_table_details")
@IdClass(OneTimeTableDetailsId.class)

public class OneTimeTableDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="PARENT_ID", nullable=false)
    private Integer    parentId ;
    
    @Id
    @Column(name="AMEND_ID", nullable=false)
    private Integer    amendId ;
    
    @Id
    @Column(name="COMPANY_ID", nullable=false, length=300)
    private String     companyId ;

    
    //--- ENTITY DATA FIELDS 
    @Column(name="ITEM_ID", nullable=false)
    private Integer    itemId ;

    @Column(name="ITEM_TYPE", length=300)
    private String     itemType ;

    @Column(name="ITEM_CODE", length=20)
    private String     itemCode ;

    @Column(name="ITEM_VALUE", length=300)
    private String     itemValue ;

    @Column(name="STATUS", length=30)
    private String     status ;

    @Column(name="DISPLAY_NAME", length=300)
    private String     displayName ;

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;
    

    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_START")
    private Date       effectiveDateStart ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_END")
    private Date       effectiveDateEnd ;

    @Column(name="CREATED_BY")
    private String     createdBy ;

    @Column(name="UPDATED_BY", length=100)
    private String     updatedBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date  updatedDate ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



