/*
 * Created on 2022-09-06 ( 11:31:29 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;



/**
 * Composite primary key for entity "RawBuildingsDetails" ( stored in table "raw_buildings_details" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class RawBuildingsDetailsId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private String     requestReferenceNo ;
    
    private Integer    customerId ;
    
    private Integer    sectionId ;
    
    private Integer    riskId ;
    
    private String     companyId ;
    
    private String     branchCode ;
    
     
}
