/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-09-02 ( Date ISO 2022-09-02 - Time 18:14:52 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.master.service;

import java.util.List;

import com.maan.eway.error.Error;
import com.maan.eway.master.req.CompanyPromcodeMasterGetReq;
import com.maan.eway.master.req.CompanyPromocodeMasterChangeStatusReq;
import com.maan.eway.master.req.CompanyPromocodeMasterGetAllReq;
import com.maan.eway.master.req.CompanyPromocodeSaveReq;
import com.maan.eway.master.req.CompanyPromocodeSchemeSaveReq;
import com.maan.eway.master.res.CompanyPromocodeMasterRes;
import com.maan.eway.res.SuccessRes;

/**
* <h2>CompanyPromocodeMasterServiceimpl</h2>
*/
public interface CompanyPromocodeMasterService  {

	List<Error> validateCompanyPromocode(CompanyPromocodeSaveReq req);

	SuccessRes insertCompanyPromocode(CompanyPromocodeSaveReq req);


	List<CompanyPromocodeMasterRes> getallCompanyPromocode(CompanyPromocodeMasterGetAllReq req);

	List<CompanyPromocodeMasterRes> getActivePromocode(CompanyPromocodeMasterGetAllReq req);

	CompanyPromocodeMasterRes getByCompanyPromocodeId(CompanyPromcodeMasterGetReq req);

	SuccessRes changestatusofCompanyPromocode(CompanyPromocodeMasterChangeStatusReq req);

	List<Error> validateSchemePromocode(CompanyPromocodeSchemeSaveReq req, String string);

	SuccessRes insertSchemePromocode(CompanyPromocodeSchemeSaveReq req);

}
