/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.master.service;

import java.util.List;

import com.maan.eway.master.req.CompanyProrataChangeStatusReq;
import com.maan.eway.master.req.CompanyProrataGetAllReq;
import com.maan.eway.master.req.CompanyProrataGetReq;
import com.maan.eway.master.req.CompanyProrataSaveReq;
import com.maan.eway.master.res.CompanyProrataGetAllRes;
import com.maan.eway.master.res.CompanyProrataGetRes;
import com.maan.eway.res.SuccessRes;
/**
* <h2>BankMasterServiceimpl</h2>
*/
public interface CompanyProrataService  {

	List<String> validateCompanyProrata(CompanyProrataSaveReq req);

	SuccessRes insertCompanyProrata(CompanyProrataSaveReq req);

	CompanyProrataGetRes getByCompanyProrata(CompanyProrataGetReq req);

	List<CompanyProrataGetAllRes> getActiveCompanyProrata(CompanyProrataGetAllReq req);

	SuccessRes changeStatusOfProrata(CompanyProrataChangeStatusReq req);

	List<CompanyProrataGetAllRes> getallComapnyProrata(CompanyProrataGetAllReq req);

	


}
