/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.master.service;


import com.maan.eway.master.req.CompanyProductChangeStatusReq;
import com.maan.eway.master.req.CompanyProductMasterGetAllReq;
import com.maan.eway.master.req.CompanyProductMasterGetReq;
import com.maan.eway.master.req.CompanyProductMasterSaveReq;
import com.maan.eway.master.req.CompanyProductMultiInsertReq;
import com.maan.eway.master.req.CoverMasterGetReq;
import com.maan.eway.master.req.ProductDropDownReq;
import com.maan.eway.master.req.ProductMasterGetAllReq;
import com.maan.eway.master.req.ProductMasterGetReq;
import com.maan.eway.master.req.ProductMasterSaveReq;
import com.maan.eway.master.res.CompanyProductConfigRes;
import com.maan.eway.master.res.CompanyProductGetAllRes;
import com.maan.eway.master.res.CompanyProductMasterRes;
import com.maan.eway.master.res.ProductGetAllRes;
import com.maan.eway.master.res.ProductMasterRes;
import com.maan.eway.error.Error;
import com.maan.eway.res.CompanyProductDropDownRes;
import com.maan.eway.res.DropDownRes;
import com.maan.eway.res.SuccessRes;

import java.util.List;
/**
* <h2>BankMasterServiceimpl</h2>
*/
public interface CompanyProductMasterService  {

	List<String> validateCompanyProductDetails(List<CompanyProductMultiInsertReq> req);

	SuccessRes insertCompanyProductDetails(List<CompanyProductMultiInsertReq> req);

	List<CompanyProductGetAllRes> getallCompanyProductDetails(CompanyProductMasterGetAllReq req);

	List<CompanyProductGetAllRes> getActiveCompanyProductDetails(CompanyProductMasterGetAllReq req);

	CompanyProductMasterRes getByCompanyProductId(CompanyProductMasterGetReq req);

	List<ProductGetAllRes> getallNonSelectedCompanyProducts(CompanyProductMasterGetAllReq req);

	List<CompanyProductDropDownRes> getCompanyProductMasterDropdown(CompanyProductMasterGetAllReq req);

	SuccessRes changeStatusOfCompanyProduct(CompanyProductChangeStatusReq req);

	List<String> validateUpdateCompanyProductDetails(CompanyProductMasterSaveReq req);

	SuccessRes updateCompanyProductDetails(CompanyProductMasterSaveReq req);

	CompanyProductConfigRes getByCompanyProductConfig(CompanyProductMasterGetReq req);


}
