/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.master.service;

import com.maan.eway.master.req.BankMasterGetAllReq;
import com.maan.eway.master.req.BankMasterGetReq;
import com.maan.eway.master.req.BankMasterSaveReq;
import com.maan.eway.master.req.CurrencyMasterGetAllReq;
import com.maan.eway.master.req.CurrencyMasterGetReq;
import com.maan.eway.master.req.CurrencyMasterSaveReq;
import com.maan.eway.master.req.OccupationMasterGetAllReq;
import com.maan.eway.master.req.OccupationMasterGetReq;
import com.maan.eway.master.req.OccupationMasterSaveReq;
import com.maan.eway.master.req.ProductMasterGetAllReq;
import com.maan.eway.master.req.ProductMasterGetReq;
import com.maan.eway.master.req.ProductMasterSaveReq;
import com.maan.eway.master.req.RegionMasterGetAllReq;
import com.maan.eway.master.req.RegionMasterGetReq;
import com.maan.eway.master.req.RegionMasterSaveReq;
import com.maan.eway.master.res.BankMasterRes;
import com.maan.eway.master.res.CurrencyMasterRes;
import com.maan.eway.master.res.OccupationMasterRes;
import com.maan.eway.master.res.ProductMasterRes;
import com.maan.eway.master.res.RegionMasterRes;
import com.maan.eway.error.Error;
import com.maan.eway.res.DropDownRes;
import com.maan.eway.res.SuccessRes;

import java.util.List;
/**
* <h2>BankMasterServiceimpl</h2>
*/
public interface OccupationMasterService  {

	List<Error> validateOccupation(OccupationMasterSaveReq req);

	SuccessRes insertOccupation(OccupationMasterSaveReq req);

	List<OccupationMasterRes> getallOccupation(OccupationMasterGetAllReq req);

	OccupationMasterRes getByOccupationId(OccupationMasterGetReq req);

	List<OccupationMasterRes> getActiveOccupation(OccupationMasterGetAllReq req);

}
