/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.master.service;

import java.util.List;

import com.maan.eway.error.Error;
import com.maan.eway.master.req.WarrantyChangeStatusReq;
import com.maan.eway.master.req.WarrantyMasterGetReq;
import com.maan.eway.master.req.WarrantyMasterGetallReq;
import com.maan.eway.master.req.WarrantyMasterSaveReq;
import com.maan.eway.master.res.WarrantyMasterRes;
import com.maan.eway.res.SuccessRes;

/**
* <h2>BankMasterServiceimpl</h2>
*/
public interface WarrantyMasterService  {

	List<Error> validateWarranty(WarrantyMasterSaveReq req);

	SuccessRes saveWarranty(WarrantyMasterSaveReq req);

	List<WarrantyMasterRes> getallWarranty(WarrantyMasterGetallReq req);

	List<WarrantyMasterRes> getActiveWarranty(WarrantyMasterGetallReq req);

	WarrantyMasterRes getByWarrantyId(WarrantyMasterGetReq req);

	SuccessRes changeStatusOfWarranty(WarrantyChangeStatusReq req);

	

}
