/*
 * Java domain class for entity "CurrencyMaster" 
 * Created on 2022-09-02 ( Date ISO 2022-09-02 - Time 18:14:52 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.eway.domain;

import java.io.Serializable;

import lombok.*;
import java.math.BigDecimal;
import java.util.Date;


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;



/**
 * Domain class for entity "CurrencyMaster"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class CurrencyMasterDto implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------
	@JsonProperty("Currencyid")
    private Integer    currencyId   ;
	@JsonProperty("Effectivedatestart")
    private Date       effectiveDateStart ;
	@JsonProperty("Effectivedateend")
    private Date       effectiveDateEnd ;
	@JsonProperty("Exminlmt")
    private BigDecimal exMinlmt     ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	@JsonProperty("Currencyname")
    private String     currencyName ;
	@JsonProperty("Entrydate")
    private Date       entryDate    ;
	@JsonProperty("Remarks")
    private String     remarks      ;
	@JsonProperty("Status")
    private String     status       ;
	@JsonProperty("Rsacode")
    private String     rsacode      ;
	@JsonProperty("Sno")
    private Long       sno          ;
	@JsonProperty("Countryid")
    private Long       countryId    ;
	@JsonProperty("Displayorder")
    private Integer    displayOrder ;
	@JsonProperty("Shortname")
    private String     shortName    ;
	@JsonProperty("Rfactor")
    private Byte       rfactor      ;
	@JsonProperty("Subcurrency")
    private String     subCurrency  ;
	@JsonProperty("Exmaxlmt")
    private BigDecimal exMaxlmt     ;

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

      
	  
	  
}
