/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:27 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.service;
import com.maan.eway.bean.InsuranceCompanyMaster;

import java.util.List;
/**
* <h2>InsuranceCompanyMasterServiceimpl</h2>
*/
public interface InsuranceCompanyMasterService  {

InsuranceCompanyMaster create(InsuranceCompanyMaster d);
InsuranceCompanyMaster update(InsuranceCompanyMaster d);
//InsuranceCompanyMaster getOne(long id) ;
 List<InsuranceCompanyMaster> getAll();
long getTotal();
//boolean delete(long id);

}
