/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-09-06 ( Date ISO 2022-09-06 - Time 11:31:30 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.service;

import com.maan.eway.req.RawPersonalAccidentSaveReq;
import com.maan.eway.res.SuccessRes;

/**
* <h2>RawPersonalAccidentServiceimpl</h2>
*/
public interface RawPersonalAccidentService  {

	SuccessRes savePersonalAccident(RawPersonalAccidentSaveReq req);

}
