/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.master.service.impl;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaDelete;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.CriteriaUpdate;
import javax.persistence.criteria.Order;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import javax.persistence.criteria.Subquery;

import org.apache.commons.lang3.StringUtils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.dozer.DozerBeanMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.google.gson.Gson;
import com.maan.eway.bean.CompanyProductMaster;
import com.maan.eway.bean.ListItemValue;
import com.maan.eway.bean.ProductMaster;
import com.maan.eway.error.Error;
import com.maan.eway.master.req.ProductChangeStatusReq;
import com.maan.eway.master.req.ProductMasterGetAllReq;
import com.maan.eway.master.req.ProductMasterGetReq;
import com.maan.eway.master.req.ProductMasterSaveReq;
import com.maan.eway.master.res.ProductMasterRes;
import com.maan.eway.master.service.ProductMasterService;
import com.maan.eway.repository.ListItemValueRepository;
import com.maan.eway.repository.ProductMasterRepository;
import com.maan.eway.res.DropDownRes;
import com.maan.eway.res.SuccessRes;
import com.maan.eway.service.impl.BasicValidationService;
/**
* <h2>ProductMasterServiceimpl</h2>
*/
@Service
@Transactional
public class ProductMasterServiceImpl implements ProductMasterService {

@PersistenceContext
private EntityManager em;

@Autowired
private ProductMasterRepository repo;

@Autowired
private BasicValidationService basicvalidateService;

@Autowired
private ListItemValueRepository listRepo ;

Gson json = new Gson();

private Logger log=LogManager.getLogger(ProductMasterServiceImpl.class);

	//************************************************INSERT/UPDATE PRODUCT DETAILS******************************************************\\
	@Transactional
	@Override
	public SuccessRes insertProduct(ProductMasterSaveReq req) {
	    SimpleDateFormat sdformat = new SimpleDateFormat("dd/MM/YYYY");
		SuccessRes res = new SuccessRes();
		ProductMaster saveData = new ProductMaster();
		List<ProductMaster> list = new ArrayList<ProductMaster>();
		DozerBeanMapper dozerMapper = new  DozerBeanMapper();
		
		try {
			Integer amendId = 0 ;
			Calendar cal = new GregorianCalendar();
			cal.setTime(req.getEffectiveDateStart());  cal.set(Calendar.HOUR_OF_DAY, 23); cal.set(Calendar.MINUTE, 59);
			Date startDate = cal.getTime() ;
			Date today = new Date();
			cal.setTime(req.getEffectiveDateStart());  cal.add(Calendar.DAY_OF_MONTH, -1); cal.set(Calendar.HOUR_OF_DAY, today.getHours()); cal.set(Calendar.MINUTE, today.getMinutes());
			cal.set(Calendar.SECOND, today.getSeconds());
			Date oldEndDate = cal.getTime() ;
			cal.setTime(req.getEffectiveDateStart());  cal.set(Calendar.HOUR_OF_DAY, today.getHours()); cal.set(Calendar.MINUTE, today.getMinutes()) ;
			cal.set(Calendar.SECOND, today.getSeconds());
			Date effDate = cal.getTime();
			Date endDate = req.getEffectiveDateEnd();
			cal.setTime(req.getEffectiveDateEnd());  cal.set(Calendar.HOUR_OF_DAY, 23); cal.set(Calendar.MINUTE, 50) ;
			endDate = cal.getTime() ;
			
			String productId="";
			
			if (StringUtils.isBlank(req.getProductId().toString())) {
					// Save
				    //Long totalCount = repo.count();
					Long totalCount =getProductMasterTableCount();
					productId = Long.valueOf(totalCount + 01).toString();
					saveData.setProductId(Integer.valueOf(productId));
					saveData.setProductName(req.getProductName());
					res.setResponse("Saved Successfully ");
					res.setSuccessId(productId);
	
				} else {
					// Update
					// Get Less than Equal Today Record 
					// Criteria
					productId=req.getProductId();
					CriteriaBuilder cb = em.getCriteriaBuilder();
					CriteriaQuery<ProductMaster> query = cb.createQuery(ProductMaster.class);
	
					// Find All
					Root<ProductMaster> b = query.from(ProductMaster.class);
	
					// Select
					query.select(b);
	
					// Effective Date Max Filter
					Subquery<Long> effectiveDate = query.subquery(Long.class);
					Root<ProductMaster> ocpm1 = effectiveDate.from(ProductMaster.class);
					effectiveDate.select(cb.max(ocpm1.get("effectiveDateStart")));
					Predicate a1 = cb.equal(ocpm1.get("productId"), b.get("productId"));
					Predicate a2 = cb.lessThanOrEqualTo(ocpm1.get("effectiveDateStart") , startDate);
					effectiveDate.where(a1,a2);
	
					// Order By
				//	List<Order> orderList = new ArrayList<Order>();
				//	orderList.add(cb.asc(b.get("branchName")));
					
					// Where
					Predicate n1 = cb.equal(b.get("status"), "Y");
					Predicate n2 = cb.equal(b.get("effectiveDateStart"), effectiveDate);
					Predicate n3 =  cb.equal(b.get("productId"), req.getProductId() );
	
					query.where(n1, n2, n3);//.orderBy(orderList);
	
					// Get Result
					TypedQuery<ProductMaster> result = em.createQuery(query);
					list = result.getResultList();
					
					if( list.size() > 0) {
						repo.delete(list.get(0));
						// Amend ID
						if( list.get(0).getEffectiveDateStart().before(startDate)   ) {
							String startDatewithoutTime = sdformat.format(startDate) ;
							String oldDatewithoutTime = sdformat.format(list.get(0).getEffectiveDateStart()) ;
							
							if(startDatewithoutTime.equalsIgnoreCase(oldDatewithoutTime) ) {
								amendId = list.get(0).getAmendId() + 1 ;
							}
						}
					} 
					res.setResponse("Updated Successfully ");
					res.setSuccessId(productId);
				}
			
			    dozerMapper.map(req, saveData );
				saveData.setProductId(Integer.valueOf(productId));
				saveData.setProductName(req.getProductName());
				saveData.setEffectiveDateStart(effDate);
				saveData.setEffectiveDateEnd(endDate);
				saveData.setStatus(req.getStatus());
				saveData.setEntryDate(new Date());
				saveData.setAmendId(amendId);
				
				ListItemValue icon = listRepo.findByItemTypeAndItemCodeAndStatus("PRODUCT_ICONS" , req.getProductIconId() ,"Y");
				saveData.setProductIconId(Integer.valueOf(icon.getItemCode()));
				saveData.setProductIconName(icon.getItemValue());
				repo.saveAndFlush(saveData);
				
				if(list.size() > 0 ) {
					// Update Old Record
					ProductMaster lastRecord = list.get(0) ;
					lastRecord.setEffectiveDateEnd(oldEndDate);
					repo.saveAndFlush(lastRecord);
					
					
				}
				
				log.info("Saved Details is ---> " + json.toJson(saveData));
				
	} catch (Exception e) {
			e.printStackTrace();
			log.info("Exception is --->" + e.getMessage());
			return null;
		}
		return res;
	}
	
	
	@Override
	public List<Error> validateProductDetails(ProductMasterSaveReq req) {
		List<Error> errorList = new ArrayList<Error>();
		try {
		
			if (StringUtils.isBlank(req.getProductName())) {
				errorList.add(new Error("01", "ProductName", "Please Select Product  Name "));
			}else if (req.getProductName().length() > 100){
				errorList.add(new Error("01","ProductName", "Please Enter Product  Name within 100 Characters")); 
			}else if (StringUtils.isBlank(req.getProductId())) {
				List<ProductMaster> ProductList = getProductNameExistDetails(req.getProductName());
				if (ProductList.size()>0 ) {
					errorList.add(new Error("01", "Product", "This Product Name Already Exist "));
				}
			}else  {
				List<ProductMaster> ProductList =  getProductNameExistDetails(req.getProductName() );
				if (ProductList.size()>0 &&  (! req.getProductId().equalsIgnoreCase(ProductList.get(0).getProductId().toString())) ) {
					errorList.add(new Error("01", "Product", "This Product Name Already Exist "));
				}
				
			}
	
			if (StringUtils.isBlank(req.getProductIconId()) ) {
				errorList.add(new Error("02", "ProductIconId", "Please Select Product Icon"));
			} else if (! req.getProductIconId().matches("[0-9]+")  ) {
				errorList.add(new Error("02", "ProductIconId", "Please Select  Valid Product Icon"));
			}else {
				ListItemValue icon = listRepo.findByItemTypeAndItemCodeAndStatus("PRODUCT_ICONS" , req.getProductIconId() ,"Y");
				if( icon ==null ) {
					errorList.add(new Error("02", "ProductIconId", "Please Select  Valid Product Icon"));	
				}
			}
			
			if (StringUtils.isBlank(req.getRemarks()) ) {
				errorList.add(new Error("03", "Remark", "Please Select Remark "));
			}else if (req.getRemarks().length() > 100){
				errorList.add(new Error("03","Remark", "Please Enter Remark within 100 Characters")); 
			}
			
			// Date Validation 
			Calendar cal = new GregorianCalendar();
			Date today = new Date();
			cal.setTime(today);cal.add(Calendar.DAY_OF_MONTH, -1);cal.set(Calendar.HOUR_OF_DAY, 23);cal.set(Calendar.MINUTE, 50);
			today = cal.getTime();
			if (req.getEffectiveDateStart() == null ) {
				errorList.add(new Error("04", "EffectiveDateStart", "Please Enter Effective Date Start "));
	
			} else if (req.getEffectiveDateStart().before(today)) {
				errorList.add(new Error("04", "EffectiveDateStart", "Please Enter Effective Date Start as Future Date"));
			} else if (req.getEffectiveDateEnd() == null ) {
				errorList.add(new Error("04", "EffectiveDateEnd", "Please Enter Effective Date End "));
	
			} else if (req.getEffectiveDateEnd().before(req.getEffectiveDateStart()) || req.getEffectiveDateEnd().equals(req.getEffectiveDateStart())) {
				errorList.add(new Error("04", "EffectiveDateStart", "Please Enter Effective Date End  is After Effective Date Start"));
			} 
			//Status Validation
			if (StringUtils.isBlank(req.getStatus())) {
				errorList.add(new Error("05", "Status", "Please Enter Status"));
			} else if (req.getStatus().length() > 1) {
				errorList.add(new Error("05", "Status", "Enter Status 1 Character Only"));
			}else if(!("Y".equals(req.getStatus())||"N".equals(req.getStatus()))) {
				errorList.add(new Error("05", "Status", "Enter Status Y or N Only"));
			}
			
			if (StringUtils.isBlank(req.getPaymentYn())) {
				errorList.add(new Error("06", "Payment", "Please Select Payment Type"));
			} else if (req.getPaymentYn().length() > 1) {
				errorList.add(new Error("06", "Payment", "Enter Payment Type 1 Character Only"));
			}else if(!("Y".equals(req.getPaymentYn())||"N".equals(req.getPaymentYn()))) {
				errorList.add(new Error("06", "Payment", "Enter Payment Type Y or N Only"));
			}
			
			if (StringUtils.isBlank(req.getCommissionVatYn())) {
				errorList.add(new Error("05", "CommissionVat", "Please Select CommissionVat Type"));
			} else if (req.getCommissionVatYn().length() > 1) {
				errorList.add(new Error("05", "CommissionVat", "Enter CommissionVat Type 1 Character Only"));
			}else if(!("Y".equals(req.getCommissionVatYn())||"N".equals(req.getCommissionVatYn()))) {
				errorList.add(new Error("05", "CommissionVat", "Enter CommissionVat Y or N Only"));
			}
			
			if (StringUtils.isBlank(req.getCheckerYn())) {
				errorList.add(new Error("05", "Checker", "Please Select Checker"));
			} else if (req.getCheckerYn().length() > 1) {
				errorList.add(new Error("05", "Checker", "Enter Checker 1 Character Only"));
			}else if(!("Y".equals(req.getCheckerYn())||"N".equals(req.getCheckerYn()))) {
				errorList.add(new Error("05", "Checker", "Enter Checker Y or N Only"));
			}
			
			if (StringUtils.isBlank(req.getMakerYn())) {
				errorList.add(new Error("05", "Maker", "Please Select Maker"));
			} else if (req.getMakerYn().length() > 1) {
				errorList.add(new Error("05", "Maker", "Enter Maker 1 Character Only"));
			}else if(!("Y".equals(req.getMakerYn())||"N".equals(req.getMakerYn()))) {
				errorList.add(new Error("05", "Maker", "Enter Maker Y or N Only"));
			}
			
			if (StringUtils.isBlank(req.getCustConfirmYn())) {
				errorList.add(new Error("05", "CustomerConfirmation", "Please Select CustomerConfirmation"));
			} else if (req.getCustConfirmYn().length() > 1) {
				errorList.add(new Error("05", "CustomerConfirmation", "Enter CustomerConfirmation 1 Character Only"));
			}else if(!("Y".equals(req.getCustConfirmYn())||"N".equals(req.getCustConfirmYn()))) {
				errorList.add(new Error("05", "CustomerConfirmation", "Enter CustomerConfirmation Y or N Only"));
			}
			
			if(StringUtils.isBlank(req.getSumInsuredStart())) {
				errorList.add(new Error("02", "Sum Insured Start", "Plese Enter Sum Insured Start  " ));
			} else if (! req.getSumInsuredStart().matches("[0-9.]+") ) {
				errorList.add(new Error("02", "Sum Insured Start", "Plese Enter Valid Number Sum Insured Start "  ));
			}
			if(StringUtils.isBlank(req.getSumInsuredEnd())) {
				errorList.add(new Error("02", "Sum Insured End", "Plese Enter Sum Insured End " ));
			} else if (! req.getSumInsuredEnd().matches("[0-9.]+") ) {
				errorList.add(new Error("02", "Sum Insured End", "Plese Enter Valid Number Sum Insured End  "  ));
			} else if (StringUtils.isNotBlank(req.getSumInsuredStart()) && StringUtils.isBlank(req.getSumInsuredEnd())  ) {
				if (Long.valueOf(req.getSumInsuredStart()) > Long.valueOf(req.getSumInsuredEnd()) ) {
					errorList.add(new Error("02", "Sum Insured End", "Sum Insured Start Greater Than Sum Insured End " ));
				}
			}
			
			if (StringUtils.isBlank(req.getProductCategory())) {
				errorList.add(new Error("08", "ProductCategory", "Please Select Product  Category "));
			}else if (req.getProductCategory().length() > 25) {
				errorList.add(new Error("08", "ProductCategory", "Please Enter Product Category within 25 Characters"));
			}
			
			if (StringUtils.isBlank(req.getPaymentRedirUrl())) {
				errorList.add(new Error("08", "PaymentRedirUrl", "Please Select PaymentRedirUrl  Category "));
			}else if (req.getPaymentRedirUrl().length() > 500) {
				errorList.add(new Error("10", "PaymentRedirUrl", "Please Enter PaymentRedirUrl within 500 Characters"));
			}
			
			if (StringUtils.isBlank(req.getAppLoginUrl())) {
				errorList.add(new Error("08", "AppLoginUrl", "Please Select AppLoginUrl "));
			}else if (req.getAppLoginUrl().length() > 100) {
				errorList.add(new Error("11", "AppLoginUrl", "Please Enter AppLoginUrl within 100 Characters"));
			}
			
			if (StringUtils.isBlank(req.getCreatedBy())) {
				errorList.add(new Error("08", "CreatedBy", "Please Enter CreatedBy"));
			}else if (req.getCreatedBy().length() > 50) {
				errorList.add(new Error("11", "CreatedBy", "Please Enter CreatedBy within 100 Characters"));
			}
			
			if (StringUtils.isBlank(req.getCoreAppCode())) {
				errorList.add(new Error("08", "CoreAppCode", "Please Enter CoreAppCode"));
			}else if (req.getCoreAppCode().length() > 20) {
				errorList.add(new Error("11", "CoreAppCode", "Please Enter CoreAppCode within 20 Characters"));
			}
			
			if (StringUtils.isBlank(req.getTiraCode())) {
				errorList.add(new Error("08", "TiraCode", "Please Enter TiraCode"));
			}else if (req.getTiraCode().length() > 20) {
				errorList.add(new Error("11", "TiraCode", "Please Enter TiraCode within 20 Characters"));
			}
			
		} catch (Exception e) {
			log.error(e);
			e.printStackTrace();
			errorList.add(new Error("12", "Common Error", e.getMessage()));
		}
		return errorList;
	}
	
	public Long getProductMasterTableCount() {
	
		Long data = 0L;
		try {
	
			List<Long> list = new ArrayList<Long>();
			// Find Latest Record
			CriteriaBuilder cb = em.getCriteriaBuilder();
			CriteriaQuery<Long> query = cb.createQuery(Long.class);
	
			// Find All
			Root<ProductMaster> b = query.from(ProductMaster.class);
	
			// Select
			query.multiselect(cb.count(b));
	
			// Effective Date Max Filter
			Subquery<Long> effectiveDate = query.subquery(Long.class);
			Root<ProductMaster> ocpm1 = effectiveDate.from(ProductMaster.class);
			effectiveDate.select(cb.max(ocpm1.get("effectiveDateStart")));
			Predicate a1 = cb.equal(ocpm1.get("productId"), b.get("productId"));
			effectiveDate.where(a1);
	
			Predicate n1 = cb.equal(b.get("effectiveDateStart"), effectiveDate);
			query.where(n1);
			// Get Result
			TypedQuery<Long> result = em.createQuery(query);
			list = result.getResultList();
	
			data = list.get(0);
	
		} catch (Exception e) {
			e.printStackTrace();
			log.info(e.getMessage());
	
		}
		return data;
	}
	
	
	public List<ProductMaster> getProductNameExistDetails(String productName) {
		List<ProductMaster> list = new ArrayList<ProductMaster>();
		try {
			// Find Latest Record
			CriteriaBuilder cb = em.getCriteriaBuilder();
			CriteriaQuery<ProductMaster> query = cb.createQuery(ProductMaster.class);
	
			// Find All
			Root<ProductMaster> b = query.from(ProductMaster.class);
	
			// Select
			query.select(b);
	
			// Effective Date Max Filter
			Subquery<Long> effectiveDate = query.subquery(Long.class);
			Root<ProductMaster> ocpm1 = effectiveDate.from(ProductMaster.class);
			effectiveDate.select(cb.max(ocpm1.get("effectiveDateStart")));
			Predicate a1 = cb.equal(ocpm1.get("productId"), b.get("productId"));
			effectiveDate.where(a1);
	
			Predicate n1 = cb.equal(b.get("effectiveDateStart"), effectiveDate);
			Predicate n2 = cb.equal(b.get("productName"), productName );	
			query.where(n1,n2);
			// Get Result
			TypedQuery<ProductMaster> result = em.createQuery(query);
			list = result.getResultList();		
		
		} catch (Exception e) {
			e.printStackTrace();
			log.info(e.getMessage());
	
		}
		return list;
	}
	
	///*********************************************************************GET ALL******************************************************\\
	@Override
	public List<ProductMasterRes> getallProductDetails(ProductMasterGetAllReq req) {
		List<ProductMasterRes> resList = new ArrayList<ProductMasterRes>();
		DozerBeanMapper dozerMapper = new  DozerBeanMapper();

		try {
			Date today  = new Date();
			Calendar cal = new GregorianCalendar(); 
			cal.setTime(today);
			cal.set(Calendar.HOUR_OF_DAY, 23);
			cal.set(Calendar.MINUTE, 1);
			today   = cal.getTime();
			
			List<ProductMaster> list = new ArrayList<ProductMaster>();
			//Pagination
			int limit = StringUtils.isBlank(req.getLimit()) ? 0 : Integer.valueOf(req.getLimit());
			int offset = StringUtils.isBlank(req.getOffset()) ? 100 : Integer.valueOf(req.getOffset());
	
			// Find Latest Record
			CriteriaBuilder cb = em.getCriteriaBuilder();
			CriteriaQuery<ProductMaster> query = cb.createQuery(ProductMaster.class);
	
			// Find All
			Root<ProductMaster> b = query.from(ProductMaster.class);
	
			// Select
			query.select(b);
	
			// Effective Date Max Filter
			Subquery<Long> effectiveDate = query.subquery(Long.class);
			Root<ProductMaster> ocpm1 = effectiveDate.from(ProductMaster.class);
			effectiveDate.select(cb.max(ocpm1.get("effectiveDateStart")));
			Predicate a1 = cb.equal(ocpm1.get("productId"), b.get("productId"));
			Predicate a2 = cb.lessThanOrEqualTo(ocpm1.get("effectiveDateStart"), today);
			effectiveDate.where(a1,a2);
	
			// Order By
			List<Order> orderList = new ArrayList<Order>();
			orderList.add(cb.asc(b.get("productName")));
			
			// Where
			Predicate n1 = cb.equal(b.get("effectiveDateStart"), effectiveDate);
			query.where(n1).orderBy(orderList);
	
			// Get Result
			TypedQuery<ProductMaster> result = em.createQuery(query);
			result.setFirstResult(limit * offset);
			result.setMaxResults(offset);
			list = result.getResultList();
			
			// Map
			for (ProductMaster data : list) {
				ProductMasterRes res = new ProductMasterRes();
	
				res = dozerMapper.map(data, ProductMasterRes.class);
				res.setProductId(data.getProductId().toString());
				resList.add(res);
			}
	
		} catch (Exception e) {
			e.printStackTrace();
			log.info(e.getMessage());
			return null;
	
		}
		return resList;
	}
	
	///*********************************************************************GET BY ID******************************************************\\
	@Override
	public ProductMasterRes getByProductCode(ProductMasterGetReq req) {
		ProductMasterRes res = new ProductMasterRes();
		DozerBeanMapper dozerMapper = new  DozerBeanMapper();

		SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
	
		try {
			Date today  = new Date();
			Calendar cal = new GregorianCalendar(); 
			cal.setTime(today);
			cal.set(Calendar.HOUR_OF_DAY, 23);
			cal.set(Calendar.MINUTE, 1);
			today   = cal.getTime();
			
			List<ProductMaster> list = new ArrayList<ProductMaster>();
			// Find Latest Record
			CriteriaBuilder cb = em.getCriteriaBuilder();
			CriteriaQuery<ProductMaster> query = cb.createQuery(ProductMaster.class);
	
			// Find All
			Root<ProductMaster> b = query.from(ProductMaster.class);
	
			// Select
			query.select(b);
	
			// Effective Date Max Filter
			Subquery<Long> effectiveDate = query.subquery(Long.class);
			Root<ProductMaster> ocpm1 = effectiveDate.from(ProductMaster.class);
			effectiveDate.select(cb.max(ocpm1.get("effectiveDateStart")));
			Predicate a1 = cb.equal(ocpm1.get("productId"), b.get("productId"));
			Predicate a2 = cb.lessThanOrEqualTo(ocpm1.get("effectiveDateStart"), today);
			effectiveDate.where(a1,a2);
	
			// Order By
			List<Order> orderList = new ArrayList<Order>();
			orderList.add(cb.desc(b.get("effectiveDateStart")));
	
			// Where
			Predicate n1 = cb.equal(b.get("effectiveDateStart"), effectiveDate);
			Predicate n2 = cb.equal(b.get("productId"), req.getProductId() );
	
			query.where(n1,n2).orderBy(orderList);
	
			// Get Result
			TypedQuery<ProductMaster> result = em.createQuery(query);
			list = result.getResultList();
			res = dozerMapper.map(list.get(0) , ProductMasterRes.class);
			res.setProductId(list.get(0).getProductId().toString());
			res.setEntryDate(list.get(0).getEntryDate());
			res.setEffectiveDateStart(list.get(0).getEffectiveDateStart());
		} catch (Exception e) {
			e.printStackTrace();
			log.info("Exception is ---> " + e.getMessage());
			return null;
		}
		return res;
	}
	
	//**********************************************************DROPDOWN********************************************************************\\
	@Override
	public List<DropDownRes> getProductMasterDropdown() {
		List<DropDownRes> resList = new ArrayList<DropDownRes>();
		try {
			Date today  = new Date();
			Calendar cal = new GregorianCalendar(); 
			cal.setTime(today);
			cal.set(Calendar.HOUR_OF_DAY, 23);
			cal.set(Calendar.MINUTE, 1);
			today   = cal.getTime();
			
			// Criteria
			CriteriaBuilder cb = em.getCriteriaBuilder();
			CriteriaQuery<ProductMaster> query = cb.createQuery(ProductMaster.class);
			List<ProductMaster> list = new ArrayList<ProductMaster>();
			
			// Find All
			Root<ProductMaster>    c = query.from(ProductMaster.class);		
			
			// Select
			query.select(c );
			
		
			// Order By
			List<Order> orderList = new ArrayList<Order>();
			orderList.add(cb.asc(c.get("productName")));
			
			// Effective Date Max Filter
			Subquery<Long> effectiveDate = query.subquery(Long.class);
			Root<ProductMaster> ocpm1 = effectiveDate.from(ProductMaster.class);
			effectiveDate.select(cb.max(ocpm1.get("effectiveDateStart")));
			javax.persistence.criteria.Predicate a1 = cb.equal(c.get("productId"),ocpm1.get("productId") );
			javax.persistence.criteria.Predicate a2 = cb.lessThanOrEqualTo(ocpm1.get("effectiveDateStart"), today);
			effectiveDate.where(a1,a2);
			
		    // Where	
			javax.persistence.criteria.Predicate n1 = cb.equal(c.get("status"), "Y");
			javax.persistence.criteria.Predicate n2 = cb.equal(c.get("effectiveDateStart"), effectiveDate);
			
			query.where(n1,n2).orderBy(orderList);
			
			// Get Result
			TypedQuery<ProductMaster> result = em.createQuery(query);			
			list =  result.getResultList();  
			
			for(ProductMaster data : list ) {
				// Response
				DropDownRes res = new DropDownRes();
				res.setCode(data.getProductId().toString());
				res.setCodeDesc(data.getProductName());
				resList.add(res);
			}		
		} catch (Exception e) {
			e.printStackTrace();
			log.info("Exception is ---> " + e.getMessage());
			return null;
		}
		return resList;
	}
	
	//************************************************GET ACTIVE PRODUCT******************************************\\
	@Override
	public List<ProductMasterRes> getActiveProductDetails(ProductMasterGetAllReq req) {
		List<ProductMasterRes> resList = new ArrayList<ProductMasterRes>();
		DozerBeanMapper dozerMapper = new  DozerBeanMapper();

		try {
			Date today  = new Date();
			Calendar cal = new GregorianCalendar(); 
			cal.setTime(today);
			cal.set(Calendar.HOUR_OF_DAY, 23);
			cal.set(Calendar.MINUTE, 1);
			today   = cal.getTime();
			
			List<ProductMaster> list = new ArrayList<ProductMaster>();
	
			//Pagination
			int limit=StringUtils.isBlank(req.getLimit())?0:Integer.valueOf(req.getLimit());
			int offset=StringUtils.isBlank(req.getOffset())?10:Integer.valueOf(req.getOffset());
			
			// Find Latest Record
			CriteriaBuilder cb = em.getCriteriaBuilder();
			CriteriaQuery<ProductMaster> query = cb.createQuery(ProductMaster.class);
	
			// Find All
			Root<ProductMaster> b = query.from(ProductMaster.class);
	
			// Select
			query.select(b);
	
			// Effective Date Max Filter
			Subquery<Long> effectiveDate = query.subquery(Long.class);
			Root<ProductMaster> ocpm1 = effectiveDate.from(ProductMaster.class);
			effectiveDate.select(cb.max(ocpm1.get("effectiveDateStart")));
			Predicate a1 = cb.equal(ocpm1.get("productId"), b.get("productId"));
			Predicate a2 = cb.lessThanOrEqualTo(ocpm1.get("effectiveDateStart"), today);
			effectiveDate.where(a1,a2);
	
			// Order By
			List<Order> orderList = new ArrayList<Order>();
			orderList.add(cb.asc(b.get("productName")));
	
			// Where
			Predicate n1 = cb.equal(b.get("effectiveDateStart"), effectiveDate);
			Predicate n3 = cb.equal(b.get("status"), "Y");
	
			query.where(n1,n3).orderBy(orderList);
	
			// Get Result
			TypedQuery<ProductMaster> result = em.createQuery(query);
			result.setFirstResult(limit * offset);
			result.setMaxResults(offset);
			list = result.getResultList();
	
			// Map
			for (ProductMaster data : list) {
				ProductMasterRes res = new ProductMasterRes();
	
				res = dozerMapper.map(data, ProductMasterRes.class);
				res.setProductId(data.getProductId().toString());
				resList.add(res);
			}
	
		} catch (Exception e) {
			e.printStackTrace();
			log.info(e.getMessage());
			return null;
	
		}
		return resList;
	}
	
	
		

		@Override
		public SuccessRes changeStatusOfProduct(ProductChangeStatusReq req) {
			SuccessRes res = new SuccessRes();
			try {
				Date today  = new Date();
				Calendar cal = new GregorianCalendar(); 
				
				ProductMaster updateRecord  = new ProductMaster();
				cal.setTime(today);
				cal.set(Calendar.HOUR_OF_DAY, 23);
				cal.set(Calendar.MINUTE, 1);
				today   = cal.getTime();
				
				List<ProductMaster> list = new ArrayList<ProductMaster>();
				// Find Latest Record
				CriteriaBuilder cb = em.getCriteriaBuilder();
				CriteriaQuery<ProductMaster> query = cb.createQuery(ProductMaster.class);
		
				// Find All
				Root<ProductMaster> b = query.from(ProductMaster.class);
		
				// Select
				query.select(b);
		
				// Effective Date Max Filter
				Subquery<Long> effectiveDate = query.subquery(Long.class);
				Root<ProductMaster> ocpm1 = effectiveDate.from(ProductMaster.class);
				effectiveDate.select(cb.max(ocpm1.get("effectiveDateStart")));
				Predicate a1 = cb.equal(ocpm1.get("productId"), b.get("productId"));
				Predicate a2 = cb.lessThanOrEqualTo(ocpm1.get("effectiveDateStart"), today);
				effectiveDate.where(a1,a2);
		
				// Order By
				List<Order> orderList = new ArrayList<Order>();
				orderList.add(cb.desc(b.get("effectiveDateStart")));
		
				// Where
				Predicate n1 = cb.equal(b.get("effectiveDateStart"), effectiveDate);
				Predicate n2 = cb.equal(b.get("productId"), req.getProductId() );
		
				query.where(n1,n2).orderBy(orderList);
		
				// Get Result
				TypedQuery<ProductMaster> result = em.createQuery(query);
				list = result.getResultList();
				updateRecord = list.get(0) ;
					
				if (req.getStatus().equalsIgnoreCase("N") )	{
						// Delete Old Records
						cal.setTime(today);
						cal.set(Calendar.HOUR_OF_DAY, 23);
						cal.set(Calendar.MINUTE, 30);
						today   = cal.getTime();
						
						// create update
						CriteriaDelete<ProductMaster> delete = cb.createCriteriaDelete(ProductMaster.class);
						Root<ProductMaster> pm = delete.from(ProductMaster.class);
						
						 // Where	
						javax.persistence.criteria.Predicate n3 = cb.equal(pm.get("productId"), req.getProductId());
						javax.persistence.criteria.Predicate n4 = cb.greaterThanOrEqualTo(pm.get("effectiveDateStart"), today);
						delete.where(n3,n4);	
						em.createQuery(delete).executeUpdate();
						// Insert Updated Record
						updateRecord.setStatus(req.getStatus());
						repo.save(updateRecord);
					
				} else if (req.getStatus().equalsIgnoreCase("Y") ) {
					// Insert Updated Record
					updateRecord.setStatus(req.getStatus());
					repo.save(updateRecord);
				}
				// perform update
				
				res.setResponse("Status Changed");
				res.setSuccessId(req.getProductId());
			} catch(Exception e ) {
				e.printStackTrace();
				log.info("Exception is ---> " + e.getMessage());
				return null;
			}
			return res;
		}

	
		
	}
