/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.master.service.impl;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.stream.Collectors;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Order;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import javax.persistence.criteria.Subquery;

import org.apache.commons.lang3.StringUtils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.dozer.DozerBeanMapper;
import org.modelmapper.ModelMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.google.gson.Gson;

import com.maan.eway.master.req.ReferalMasterGetAllReq;
import com.maan.eway.master.req.ReferalMasterGetReq;
import com.maan.eway.master.req.ReferalMasterSaveReq;
import com.maan.eway.master.res.ReferalMasterRes;
import com.maan.eway.master.service.ReferalMasterService;
import com.maan.eway.auth.token.passwordEnc;
import com.maan.eway.bean.BranchMaster;
import com.maan.eway.bean.ReferalMaster;
import com.maan.eway.error.Error;
import com.maan.eway.repository.ReferalMasterRepository;
import com.maan.eway.res.DropDownRes;
import com.maan.eway.res.SuccessRes;
import com.maan.eway.service.impl.BasicValidationService;
/**
* <h2>ReferalMasterServiceimpl</h2>
*/
@Service
@Transactional
public class ReferalMasterServiceImpl implements ReferalMasterService {

@PersistenceContext
private EntityManager em;

@Autowired
private ReferalMasterRepository repo;

@Autowired
private BasicValidationService basicvalidateService;

Gson json = new Gson();

private Logger log=LogManager.getLogger(ReferalMasterServiceImpl.class);

//************************************************INSERT/UPDATE REFERAL DETAILS******************************************************\\
@Transactional
@Override
public SuccessRes insertReferal(ReferalMasterSaveReq req) {
    SimpleDateFormat sdformat = new SimpleDateFormat("dd/MM/YYYY");
	SuccessRes res = new SuccessRes();
	ReferalMaster saveData = new ReferalMaster();
	List<ReferalMaster> list = new ArrayList<ReferalMaster>();
	 DozerBeanMapper dozerMapper = new  DozerBeanMapper();
	
	try {
		Calendar cal = new GregorianCalendar();
		cal.setTime(req.getEffectiveDate());  cal.set(Calendar.HOUR_OF_DAY, 23); cal.set(Calendar.MINUTE, 59);
		Date startDate = cal.getTime() ;
		Date today = new Date();
		cal.setTime(req.getEffectiveDate());  cal.add(Calendar.DAY_OF_MONTH, -1); cal.set(Calendar.HOUR_OF_DAY, today.getHours()); cal.set(Calendar.MINUTE, today.getMinutes());
		Date oldEndDate = cal.getTime() ;
		cal.setTime(req.getEffectiveDate());  cal.set(Calendar.HOUR_OF_DAY, today.getHours()); cal.set(Calendar.MINUTE, today.getMinutes()) ;
		Date effDate = cal.getTime();
		Date endDate = sdformat.parse("12/12/2050");
		
		
		String referalId="";
		
		if (StringUtils.isBlank(req.getReferalId().toString())) {
				// Save
			   // Integer totalCount = repo.count();
				Long totalCount=getMasterTableCount(req.getCompanyId(),req.getBranchCode());			
				referalId = Long.valueOf(totalCount + 1).toString();
				saveData.setReferalId(Integer.valueOf(referalId));
				saveData.setReferalName(req.getReferalName());
				res.setResponse("Saved Successfully ");
				res.setSuccessId(referalId);

			} else {
				// Update
				// Get Less than Equal Today Record 
				// Criteria
				referalId=req.getReferalId();
				CriteriaBuilder cb = em.getCriteriaBuilder();
				CriteriaQuery<ReferalMaster> query = cb.createQuery(ReferalMaster.class);

				// Find All
				Root<ReferalMaster> b = query.from(ReferalMaster.class);

				// Select
				query.select(b);

				// Effective Date Max Filter
				Subquery<Long> effectiveDate = query.subquery(Long.class);
				Root<ReferalMaster> ocpm1 = effectiveDate.from(ReferalMaster.class);
				effectiveDate.select(cb.max(ocpm1.get("effectiveDateStart")));
				Predicate a1 = cb.equal(ocpm1.get("referalId"), b.get("referalId"));
				Predicate a2 = cb.lessThanOrEqualTo(ocpm1.get("effectiveDateStart") , startDate);
				effectiveDate.where(a1,a2);

				// Order By
			//	List<Order> orderList = new ArrayList<Order>();
			//	orderList.add(cb.asc(b.get("branchName")));
				
				// Where
				Predicate n1 = cb.equal(b.get("status"), "Y");
				Predicate n2 = cb.equal(b.get("effectiveDateStart"), effectiveDate);
				Predicate n3 =  cb.equal(b.get("referalId"), req.getReferalId() );

				query.where(n1, n2, n3);//.orderBy(orderList);

				// Get Result
				TypedQuery<ReferalMaster> result = em.createQuery(query);
				list = result.getResultList();
				
				if( list.size() > 0) {
					repo.delete(list.get(0));
				} 
				res.setResponse("Updated Successfully ");
				res.setSuccessId(referalId);
			}
		
		    dozerMapper.map(req, saveData );
			saveData.setReferalId(Integer.valueOf(referalId));
			saveData.setReferalName(req.getReferalName());
			saveData.setEffectiveDateStart(effDate);
			saveData.setEffectiveDateEnd(endDate);
			saveData.setStatus(req.getStatus());
			saveData.setEntryDate(new Date());
			repo.saveAndFlush(saveData);
			
			if(list.size() > 0 ) {
				// Update Old Record
				ReferalMaster lastRecord = list.get(0) ;
				lastRecord.setEffectiveDateEnd(oldEndDate);
				repo.saveAndFlush(lastRecord);
			}
			
			log.info("Saved Details is ---> " + json.toJson(saveData));
			
} catch (Exception e) {
		e.printStackTrace();
		log.info("Exception is --->" + e.getMessage());
		return null;
	}
	return res;
}


@Override
public List<Error> validateReferalDetails(ReferalMasterSaveReq req) {

	List<Error> errorList = new ArrayList<Error>();

	try {
	
		if (StringUtils.isBlank(req.getReferalName()) ) {
			errorList.add(new Error("02", "ReferalName", "Please Select Referal  Name "));
		}else if (req.getReferalName().length() > 100){
			errorList.add(new Error("02","ReferalName", "Please Enter Referal  Name within 100 Characters")); 
		}else if (StringUtils.isBlank(req.getReferalId()) || req.getReferalId() == null) {
			Long ReferalCount = repo.countByReferalNameOrderByEntryDateDesc(req.getReferalName());
			if (ReferalCount > 0 ) {
				errorList.add(new Error("01", "Referal", "This Referal Alrady Exist "));
			}
		}

		if (StringUtils.isBlank(req.getRemarks()) ) {
			errorList.add(new Error("03", "Remark", "Please Select Remark "));
		}else if (req.getRemarks().length() > 100){
			errorList.add(new Error("03","Remark", "Please Enter Remark within 100 Characters")); 
		}
		
		// Date Validation 
		Calendar cal = new GregorianCalendar();
		Date today = new Date();
		cal.setTime(today);cal.add(Calendar.DAY_OF_MONTH, -1);cal.set(Calendar.HOUR_OF_DAY, 23);cal.set(Calendar.MINUTE, 50);
		today = cal.getTime();
		if (req.getEffectiveDate() == null || StringUtils.isBlank(req.getEffectiveDate().toString())) {
			errorList.add(new Error("04", "EffectiveDate", "Please Enter Effective Date "));

		} else if (req.getEffectiveDate().before(today)) {
			errorList.add(new Error("04", "EffectiveDate", "Please Enter Effective Date  as Future Date"));
		}
		//Status Validation
		if (StringUtils.isBlank(req.getStatus())) {
			errorList.add(new Error("05", "Status", "Please Enter Status"));
		} else if (req.getStatus().length() > 1) {
			errorList.add(new Error("05", "Status", "Enter Status in 1 Character Only"));
		}else if(!("Y".equals(req.getStatus())||"N".equals(req.getStatus()))) {
			errorList.add(new Error("05", "Status", "Enter Status Y or N Only"));
		}
		if (StringUtils.isBlank(req.getCompanyId()) || req.getCompanyId() == null) {
			errorList.add(new Error("06", "CompanyId", "Please Select Company Id  "));
		}else if (req.getCompanyId().length() > 20){
			errorList.add(new Error("06","CompanyId", "Please Enter Company Id within 20 Characters")); 
		}
		if (StringUtils.isBlank(req.getReferalDesc())) {
			errorList.add(new Error("06", "ReferalDesc", "Please Select Referal Description  "));
		}else if (req.getReferalDesc().length() > 300){
			errorList.add(new Error("06","ReferalDesc", "Please Enter Referal Description within 300 Characters")); 
		}
		if (StringUtils.isBlank(req.getBranchCode()) ) {
			errorList.add(new Error("07", "BranchCode", "Please Select BranchCode  "));
		}else if (req.getBranchCode().length() > 100){
			errorList.add(new Error("07","BranchCode", "Please Enter BranchCode within 100 Characters")); 
		}
		
		
	} catch (Exception e) {
		log.error(e);
		e.printStackTrace();
	}
	return errorList;
}
public Long getMasterTableCount(String InsuranceId, String branchCode) {

	Long data = 0L;
	try {

		List<Long> list = new ArrayList<Long>();
		// Find Latest Record
		CriteriaBuilder cb = em.getCriteriaBuilder();
		CriteriaQuery<Long> query = cb.createQuery(Long.class);

		// Find All
		Root<ReferalMaster> b = query.from(ReferalMaster.class);

		// Select
		query.multiselect(cb.count(b));

		// Effective Date Max Filter
		Subquery<Long> effectiveDate = query.subquery(Long.class);
		Root<ReferalMaster> ocpm1 = effectiveDate.from(ReferalMaster.class);
		effectiveDate.select(cb.max(ocpm1.get("effectiveDateStart")));
		Predicate a1 = cb.equal(ocpm1.get("referalId"), b.get("referalId"));
		Predicate a2 = cb.equal(ocpm1.get("companyId"),b.get("companyId"));
		Predicate a3 = cb.equal(ocpm1.get("branchCode"),b.get("branchCode"));
		
		effectiveDate.where(a1,a2,a3);

		Predicate n1 = cb.equal(b.get("effectiveDateStart"), effectiveDate);
		Predicate n2 = cb.equal(b.get("companyId"),InsuranceId);
		Predicate n3 = cb.equal(b.get("branchCode"), branchCode);
		query.where(n1,n2,n3);
		// Get Result
		TypedQuery<Long> result = em.createQuery(query);
		list = result.getResultList();

		data = list.get(0);

	} catch (Exception e) {
		e.printStackTrace();
		log.info(e.getMessage());

	}
	return data;
}
///*********************************************************************GET ALL******************************************************\\
@Override
public List<ReferalMasterRes> getallReferalDetails(ReferalMasterGetAllReq req) {
	List<ReferalMasterRes> resList = new ArrayList<ReferalMasterRes>();
	ModelMapper mapper = new ModelMapper();
	try {
		List<ReferalMaster> list = new ArrayList<ReferalMaster>();
		//Pagination
		int limit = StringUtils.isBlank(req.getLimit()) ? 0 : Integer.valueOf(req.getLimit());
		int offset = StringUtils.isBlank(req.getOffset()) ? 0 : Integer.valueOf(req.getOffset());

		// Find Latest Record
		CriteriaBuilder cb = em.getCriteriaBuilder();
		CriteriaQuery<ReferalMaster> query = cb.createQuery(ReferalMaster.class);

		// Find All
		Root<ReferalMaster> b = query.from(ReferalMaster.class);

		// Select
		query.select(b);

		// Effective Date Max Filter
		Subquery<Long> effectiveDate = query.subquery(Long.class);
		Root<ReferalMaster> ocpm1 = effectiveDate.from(ReferalMaster.class);
		effectiveDate.select(cb.max(ocpm1.get("effectiveDateStart")));
		Predicate a1 = cb.equal(ocpm1.get("referalId"), b.get("referalId"));
		Predicate a2 = cb.equal(ocpm1.get("companyId"),b.get("companyId"));
		Predicate a3 = cb.equal(ocpm1.get("branchCode"),b.get("branchCode"));
		
		effectiveDate.where(a1,a2,a3);

		// Order By
		List<Order> orderList = new ArrayList<Order>();
		orderList.add(cb.asc(b.get("referalName")));
		
		// Where
		Predicate n1 = cb.equal(b.get("effectiveDateStart"), effectiveDate);
		Predicate n2 = cb.equal(b.get("branchCode"),req.getBranchCode());
		
		query.where(n1,n2).orderBy(orderList);

		// Get Result
		TypedQuery<ReferalMaster> result = em.createQuery(query);
		result.setFirstResult(limit * offset);
		result.setMaxResults(offset);
		list = result.getResultList();
		
		// Map
		for (ReferalMaster data : list) {
			ReferalMasterRes res = new ReferalMasterRes();

			res = mapper.map(data, ReferalMasterRes.class);
			mapper.getConfiguration().setAmbiguityIgnored(true);
			res.setReferalId(data.getReferalId().toString());
			resList.add(res);
		}

	} catch (Exception e) {
		e.printStackTrace();
		log.info(e.getMessage());
		return null;

	}
	return resList;
}

///*********************************************************************GET BY ID******************************************************\\
@Override
public ReferalMasterRes getByReferalId(ReferalMasterGetReq req) {
	ReferalMasterRes res = new ReferalMasterRes();
	ModelMapper mapper = new ModelMapper();
	SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

	try {
		// Criteria
		CriteriaBuilder cb = em.getCriteriaBuilder();
		CriteriaQuery<ReferalMaster> query = cb.createQuery(ReferalMaster.class);
		List<ReferalMaster> list = new ArrayList<ReferalMaster>();
		
		// Find All
		Root<ReferalMaster>    c = query.from(ReferalMaster.class);		
		
		// Select
		query.select(c );
		
		// Effective Date Max Filter
		Subquery<Long> effectiveDate = query.subquery(Long.class);
		Root<ReferalMaster> ocpm1 = effectiveDate.from(ReferalMaster.class);
		effectiveDate.select(cb.max(ocpm1.get("effectiveDateStart")));
		javax.persistence.criteria.Predicate a1 = cb.equal(c.get("referalId"),ocpm1.get("referalId") );
		javax.persistence.criteria.Predicate a2 = cb.equal(c.get("companyId"),ocpm1.get("companyId"));
		javax.persistence.criteria.Predicate a3 = cb.equal(c.get("branchCode"),ocpm1.get("branchCode"));
		
		effectiveDate.where(a1,a2,a3);
		
		
		
		// Order By
		List<Order> orderList = new ArrayList<Order>();
		orderList.add(cb.asc(c.get("effectiveDateStart")));
		
	    // Where	
	
		javax.persistence.criteria.Predicate n1 = cb.equal(c.get("effectiveDateStart"), effectiveDate);		
		javax.persistence.criteria.Predicate n2 = cb.equal(c.get("referalId"),req.getReferalId()) ;
	//	javax.persistence.criteria.Predicate n3 = cb.equal(c.get("companyId"),req.getCompanyId());
		javax.persistence.criteria.Predicate n4 = cb.equal(c.get("branchCode"),req.getBranchCode());
		

		query.where(n1 ,n2,n4).orderBy(orderList);
		
		// Get Result
		TypedQuery<ReferalMaster> result = em.createQuery(query);			
		list =  result.getResultList();  
		res = mapper.map(list.get(0) , ReferalMasterRes.class);
		res.setReferalId(list.get(0).getReferalId().toString());
		res.setEntryDate(list.get(0).getEntryDate());
		res.setEffectiveDateStart(list.get(0).getEffectiveDateStart());
		res.setEffectiveDateEnd(list.get(0).getEffectiveDateEnd());
	} catch (Exception e) {
		e.printStackTrace();
		log.info("Exception is ---> " + e.getMessage());
		return null;
	}
	return res;
}

//**********************************************************DROPDOWN********************************************************************\\
@Override
public List<DropDownRes> getReferalMasterDropdown() {
	List<DropDownRes> resList = new ArrayList<DropDownRes>();
	try {
		Date today  = new Date();
		Calendar cal = new GregorianCalendar(); 
		cal.setTime(today);
		cal.set(Calendar.HOUR_OF_DAY, 23);
		cal.set(Calendar.MINUTE, 1);
		today   = cal.getTime();
		
		// Criteria
		CriteriaBuilder cb = em.getCriteriaBuilder();
		CriteriaQuery<ReferalMaster> query = cb.createQuery(ReferalMaster.class);
		List<ReferalMaster> list = new ArrayList<ReferalMaster>();
		
		// Find All
		Root<ReferalMaster>    c = query.from(ReferalMaster.class);		
		
		// Select
		query.select(c );
		
	
		// Order By
		List<Order> orderList = new ArrayList<Order>();
		orderList.add(cb.asc(c.get("referalName")));
		
		// Effective Date Max Filter
		Subquery<Long> effectiveDate = query.subquery(Long.class);
		Root<ReferalMaster> ocpm1 = effectiveDate.from(ReferalMaster.class);
		effectiveDate.select(cb.max(ocpm1.get("effectiveDateStart")));
		javax.persistence.criteria.Predicate a1 = cb.equal(c.get("referalId"),ocpm1.get("referalId") );
		javax.persistence.criteria.Predicate a2 = cb.lessThanOrEqualTo(ocpm1.get("effectiveDateStart"), today);
		effectiveDate.where(a1,a2);
		
	    // Where	
		javax.persistence.criteria.Predicate n1 = cb.equal(c.get("status"), "Y");
		javax.persistence.criteria.Predicate n2 = cb.equal(c.get("effectiveDateStart"), effectiveDate);
		
		query.where(n1,n2).orderBy(orderList);
		
		// Get Result
		TypedQuery<ReferalMaster> result = em.createQuery(query);			
		list =  result.getResultList();  
		
		for(ReferalMaster data : list ) {
			// Response
			DropDownRes res = new DropDownRes();
			res.setCode(data.getReferalId().toString());
			res.setCodeDesc(data.getReferalName());
			resList.add(res);
		}		
	} catch (Exception e) {
		e.printStackTrace();
		log.info("Exception is ---> " + e.getMessage());
		return null;
	}
	return resList;
}

//************************************************GET ACTIVE REFERAL******************************************\\
@Override
public List<ReferalMasterRes> getActiveReferalDetails(ReferalMasterGetAllReq req) {
	List<ReferalMasterRes> resList = new ArrayList<ReferalMasterRes>();
	ModelMapper mapper = new ModelMapper();
	try {
		List<ReferalMaster> list = new ArrayList<ReferalMaster>();

		//Pagination
		int limit=StringUtils.isBlank(req.getLimit())?0:Integer.valueOf(req.getLimit());
		int offset=StringUtils.isBlank(req.getOffset())?10:Integer.valueOf(req.getOffset());
		
		// Find Latest Record
		CriteriaBuilder cb = em.getCriteriaBuilder();
		CriteriaQuery<ReferalMaster> query = cb.createQuery(ReferalMaster.class);

		// Find All
		Root<ReferalMaster> b = query.from(ReferalMaster.class);

		// Select
		query.select(b);

		// Effective Date Max Filter
		Subquery<Long> effectiveDate = query.subquery(Long.class);
		Root<ReferalMaster> ocpm1 = effectiveDate.from(ReferalMaster.class);
		effectiveDate.select(cb.max(ocpm1.get("effectiveDateStart")));
		Predicate a1 = cb.equal(ocpm1.get("referalId"), b.get("referalId"));
		Predicate a2 = cb.equal(ocpm1.get("companyId"),b.get("companyId"));
		Predicate a3 = cb.equal(ocpm1.get("branchCode"),b.get("branchCode"));

		effectiveDate.where(a1,a2,a3);

		// Order By
		List<Order> orderList = new ArrayList<Order>();
		orderList.add(cb.asc(b.get("referalName")));

		// Where
		Predicate n1 = cb.equal(b.get("effectiveDateStart"), effectiveDate);
		Predicate n2 = cb.equal(b.get("status"), "Y");
		Predicate n3 = cb.equal(b.get("branchCode"),req.getBranchCode());

		query.where(n1,n2,n3).orderBy(orderList);

		// Get Result
		TypedQuery<ReferalMaster> result = em.createQuery(query);
		result.setFirstResult(limit * offset);
		result.setMaxResults(offset);
		list = result.getResultList();

		// Map
		for (ReferalMaster data : list) {
			ReferalMasterRes res = new ReferalMasterRes();

			res = mapper.map(data, ReferalMasterRes.class);
			mapper.getConfiguration().setAmbiguityIgnored(true);
			res.setReferalId(data.getReferalId().toString());
			resList.add(res);
		}

	} catch (Exception e) {
		e.printStackTrace();
		log.info(e.getMessage());
		return null;

	}
	return resList;
}

}
